import type { Breakthrough } from "./breakthroughs";

export const additionalBreakthroughs: Breakthrough[] = [
  {
    date: "2025-02-13",
    displayDate: "13 Feb 2025",
    title: "Designed enzymes catalysed multistep reactions",
    field: "Enzyme design",
    kind: "Experiment",
    result: "Researchers designed new serine hydrolases that bind and cleave ester compounds, with selected catalysts outperforming prior computationally designed esterases.",
    context: "The team tested more than 300 proteins and iterated through design and screening. Crystal structures closely matched the designs. This establishes activity for selected reactions, not a general ability to design any enzyme on demand.",
    verificationLevel: "Peer reviewed with biochemical and structural validation",
    aiRole: "Deep-learning protein design and assessment across reaction states, followed by human-led laboratory screening",
    sourceTitle: "Computational design of serine hydrolases",
    sourceUrl: "https://www.science.org/doi/10.1126/science.adu2454",
    additionalSources: [{
      title: "Baker Lab: generating enzymes with complex active sites",
      url: "https://www.bakerlab.org/2025/02/13/ai-enzymes-with-complex-active-sites/",
    }],
  },
  {
    date: "2025-01-15",
    displayDate: "15 Jan 2025",
    title: "Designed proteins neutralized lethal snake toxins",
    field: "Protein therapeutics",
    kind: "Experiment",
    result: "De novo designed binding proteins neutralized several three-finger snake toxins and protected mice from lethal neurotoxin exposure, with survival of 80-100% across the reported toxin-antitoxin combinations.",
    context: "The experiments targeted particular toxins produced by elapid snakes. They do not establish a universal antivenom, protection against every component of whole venom, or efficacy in humans.",
    verificationLevel: "Peer reviewed with biochemical and mouse validation",
    aiRole: "Generative protein design followed by laboratory selection and animal experiments",
    sourceTitle: "De novo designed proteins neutralize lethal snake venom toxins",
    sourceUrl: "https://www.nature.com/articles/s41586-024-08393-x",
    additionalSources: [{
      title: "Baker Lab: neutralizing deadly snake toxins",
      url: "https://www.bakerlab.org/2025/01/15/neutralizing-deadly-snake-toxins/",
    }],
  },
  {
    date: "2024-11-20",
    displayDate: "20 Nov 2024",
    title: "A learned decoder reduced quantum error rates",
    field: "Quantum error correction",
    kind: "Algorithm",
    result: "On the largest tested Sycamore experiments, AlphaQubit made 6% fewer decoding errors than the tensor-network comparator and 30% fewer than correlated matching.",
    context: "These are relative reductions in decoding errors on experimental data, not a 30% improvement in every quantum computation. Larger devices were tested in simulation; the reported model was still too slow for real-time correction on superconducting hardware.",
    verificationLevel: "Peer reviewed on experimental data and simulated scaling tests",
    aiRole: "Transformer-based decoding trained in simulation and fine-tuned on processor measurements",
    sourceTitle: "AlphaQubit research paper",
    sourceUrl: "https://www.nature.com/articles/s41586-024-08148-8",
    additionalSources: [{
      title: "Research teams: AlphaQubit results and limitations",
      url: "https://blog.google/innovation-and-ai/models-and-research/google-deepmind/alphaqubit-quantum-error-correction/",
    }],
  },
  {
    date: "2024-03-29",
    displayDate: "29 Mar 2024",
    title: "Learned graph search raised a Ramsey lower bound",
    field: "Extremal combinatorics",
    kind: "Bound",
    result: "Reinforcement learning found a two-colouring of the edges of K13 proving R(W5, W7) >= 14, improving the previously reported lower bound of 13.",
    context: "The paper supplies the explicit adjacency matrix and three other small-Ramsey constructions. This is a finite lower-bound certificate, not an exact determination of the Ramsey number; Wn denotes a wheel on n vertices in this paper.",
    verificationLevel: "Research preprint with explicit finite certificates and public search code",
    aiRole: "Deep cross-entropy reinforcement learning for critical graph construction",
    sourceTitle: "Reinforcement learning for graph theory, II. Small Ramsey numbers",
    sourceUrl: "https://arxiv.org/abs/2403.20055",
    additionalSources: [{
      title: "Full paper, including Theorem 3.1 and its colouring",
      url: "https://arxiv.org/html/2403.20055v1",
    }],
  },
  {
    date: "2024-03-22",
    displayDate: "22 Mar 2024",
    title: "Generated molecules became six antibacterial leads",
    field: "Drug discovery",
    kind: "Experiment",
    result: "SyntheMol generated candidate molecules together with synthesis routes. Chemists made 58 of 70 selected designs, and six showed activity against a resistant strain of Acinetobacter baumannii in laboratory testing.",
    context: "The reported antibacterial efficacy was in vitro. Two soluble candidates underwent mouse toxicity testing; infection efficacy in living animals was still a next step in the university's account. These were leads, not approved drugs.",
    verificationLevel: "Peer reviewed with synthesis and in-vitro validation",
    aiRole: "Generative search constrained by chemical building blocks and reaction rules, guided by learned antibacterial predictions",
    sourceTitle: "Generative AI for designing and validating easily synthesizable and structurally novel antibiotics",
    sourceUrl: "https://www.nature.com/articles/s42256-024-00809-7",
    additionalSources: [{
      title: "Stanford Medicine: synthesis counts and validation limits",
      url: "https://med.stanford.edu/news/all-news/2024/03/ai-drug-development.html",
    }],
  },
  {
    date: "2024-02-22",
    displayDate: "22 Feb 2024",
    title: "Tensor search reduced expensive quantum gates",
    field: "Quantum algorithms",
    kind: "Algorithm",
    result: "AlphaTensor-Quantum improved T-gate counts over existing optimization methods on a set of arithmetic circuits and recovered efficient constructions for operations used in factoring and quantum chemistry.",
    context: "This date marks the first preprint. The improvement concerns circuit resource counts, with a Karatsuba-like finite-field multiplication method among the results. It does not demonstrate a new factoring complexity bound or a working fault-tolerant quantum computer.",
    verificationLevel: "Research preprint with explicit circuit constructions and benchmark comparisons",
    aiRole: "Deep reinforcement learning for tensor decompositions that encode quantum circuits",
    sourceTitle: "Quantum Circuit Optimization with AlphaTensor",
    sourceUrl: "https://arxiv.org/abs/2402.14396",
    additionalSources: [{
      title: "Research team publication record",
      url: "https://deepmind.google/research/publications/77240/",
    }],
  },
  {
    date: "2024-02-21",
    displayDate: "21 Feb 2024",
    title: "A controller steered plasma away from tearing",
    field: "Fusion physics",
    kind: "Control",
    result: "A reinforcement-learning controller on the DIII-D tokamak kept predicted tearing-instability likelihood below a chosen threshold while maintaining high-confinement plasma performance.",
    context: "This goes beyond controlling the plasma boundary: the controller adjusted operation to avoid a core instability, including under low-torque and low-safety-factor conditions. The authors describe a proof of concept needing further tuning, not a solution to fusion energy.",
    verificationLevel: "Peer reviewed and tested on DIII-D hardware",
    aiRole: "Learned real-time control using plasma-state predictions and actuator adjustments",
    sourceTitle: "Avoiding fusion plasma tearing instability with deep reinforcement learning",
    sourceUrl: "https://www.nature.com/articles/s41586-024-07024-9",
    additionalSources: [{
      title: "US Department of Energy: experiment and scope",
      url: "https://science.osti.gov/fes/Highlights/2024/12a",
    }],
  },
  {
    date: "2023-12-20",
    displayDate: "20 Dec 2023",
    title: "Explainable models exposed an antibiotic class",
    field: "Drug discovery",
    kind: "Experiment",
    result: "Models screening roughly 12 million compounds identified chemical substructures associated with antibacterial activity. Two candidates from one structural class reduced MRSA bacterial loads in two mouse infection models.",
    context: "The researchers combined predictions of antibacterial activity and cell toxicity with physical testing. The new result was a structural class of preclinical candidates and an interpretable discovery method, not clinical evidence or a cure for antibiotic resistance.",
    verificationLevel: "Peer reviewed with in-vitro and mouse validation",
    aiRole: "Graph neural networks plus tree search to identify predictive molecular substructures",
    sourceTitle: "Discovery of a structural class of antibiotics with explainable deep learning",
    sourceUrl: "https://www.nature.com/articles/s41586-023-06887-8",
    additionalSources: [{
      title: "MIT: experimental results and discovery method",
      url: "https://news.mit.edu/2023/using-ai-mit-researchers-identify-antibiotic-candidates-1220",
    }],
  },
  {
    date: "2023-07-11",
    displayDate: "11 Jul 2023",
    title: "Diffusion designed new functional proteins",
    field: "Protein design",
    kind: "Experiment",
    result: "RFdiffusion generated protein backbones for binders, symmetric assemblies and other design tasks. Researchers experimentally characterized the structures and functions of hundreds of designed proteins.",
    context: "A designed influenza-haemagglutinin binder closely matched its model in cryo-electron microscopy. This is prospective molecular design with experimental testing, distinct from predicting the structures of existing proteins. Not every generated design works.",
    verificationLevel: "Peer reviewed with structural and functional experiments",
    aiRole: "Diffusion-based protein-backbone generation coupled to sequence design and experimental validation",
    sourceTitle: "De novo design of protein structure and function with RFdiffusion",
    sourceUrl: "https://www.nature.com/articles/s41586-023-06415-8",
    additionalSources: [{
      title: "Original paper abstract and publication record at OSTI",
      url: "https://www.osti.gov/biblio/2420884",
    }],
  },
  {
    date: "2023-05-25",
    displayDate: "25 May 2023",
    title: "A targeted antibiotic lead emerged from screening",
    field: "Drug discovery",
    kind: "Experiment",
    result: "A neural-network-guided screen identified abaucin, a compound with narrow-spectrum activity against Acinetobacter baumannii. Follow-up work showed activity in a mouse wound-infection model and a mechanism involving lipoprotein trafficking.",
    context: "The compound was identified through screening rather than generated from scratch. The result complements broad-spectrum discovery by targeting a particular pathogen; it is preclinical evidence, not an approved treatment.",
    verificationLevel: "Peer reviewed with mechanism studies and mouse validation",
    aiRole: "Predictive screening trained on measured bacterial growth inhibition",
    sourceTitle: "Deep learning-guided discovery of an antibiotic targeting Acinetobacter baumannii",
    sourceUrl: "https://www.nature.com/articles/s41589-023-01349-8",
    additionalSources: [{
      title: "MIT Jameel Clinic: original study abstract",
      url: "https://jclinic.mit.edu/research-project/deep-learning-guided-discovery-of-an-antibiotic-targeting-acinetobacter-baumannii/",
    }],
  },
  {
    date: "2021-04-29",
    displayDate: "29 Apr 2021",
    title: "Neural search helped refute graph conjectures",
    field: "Graph theory",
    kind: "Counterexample",
    result: "Adam Zsolt Wagner used reinforcement learning to find counterexamples and construction patterns for open combinatorial questions, including Collins's conjecture about peaks of two polynomial coefficient sequences of trees.",
    context: "For the Collins problem, learned examples guided a human theorem proving an infinite family of counterexamples. Another illustrative conjecture in the same paper had already been disproved, so the whole collection should not be counted as previously open problems solved autonomously.",
    verificationLevel: "Research preprint with explicit examples and mathematical proofs",
    aiRole: "Deep cross-entropy search for finite structures, with human interpretation and proof",
    sourceTitle: "Constructions in combinatorics via neural networks",
    sourceUrl: "https://arxiv.org/abs/2104.14516",
    additionalSources: [{
      title: "Full paper: Collins conjecture and Theorem 2.5",
      url: "https://arxiv.org/html/2104.14516v1",
    }],
  },
  {
    date: "2020-07-08",
    displayDate: "08 Jul 2020",
    title: "A robot searched for better hydrogen photocatalysts",
    field: "Automated chemistry",
    kind: "Experiment",
    result: "A mobile robotic chemist performed 688 experiments over eight days, using batched Bayesian search to investigate a ten-variable space of photocatalyst mixtures for hydrogen production.",
    context: "The system used ordinary laboratory instruments and updated its experiment choices from measurements. Researchers defined the chemistry, equipment and search space; the result demonstrates bounded autonomous optimization rather than unrestricted scientific agency.",
    verificationLevel: "Peer reviewed with physical experiments and public optimization code",
    aiRole: "Bayesian experimental optimization coupled to mobile laboratory robotics",
    sourceTitle: "A mobile robotic chemist",
    sourceUrl: "https://www.nature.com/articles/s41586-020-2442-2",
    additionalSources: [{
      title: "Authors' Bayesian optimizer implementation",
      url: "https://github.com/CooperComputationalCaucus/kuka_optimizer",
    }],
  },
  {
    date: "2017-12-13",
    displayDate: "13 Dec 2017",
    title: "Neural screening revealed two new exoplanets",
    field: "Astronomy",
    kind: "Prediction",
    result: "A convolutional neural network ranked weak transit signals in Kepler data, helping researchers discover and statistically validate Kepler-80g and Kepler-90i. The latter became the eighth known planet in its system.",
    context: "This date is the paper's first preprint, already accepted by the Astronomical Journal. Astronomers conducted the candidate search and statistical validation; model confidence alone did not establish that a signal was a planet.",
    verificationLevel: "Peer reviewed with statistical validation of observational signals",
    aiRole: "Neural classification of transit candidates followed by astronomical validation",
    sourceTitle: "Identifying Exoplanets with Deep Learning",
    sourceUrl: "https://arxiv.org/abs/1712.05044",
    additionalSources: [{
      title: "Astronomical Journal publication",
      url: "https://doi.org/10.3847/1538-3881/aa9e09",
    }],
  },
];
