export type BreakthroughKind =
  | "Benchmark"
  | "Algorithm"
  | "Construction"
  | "Counterexample"
  | "Proof"
  | "Formalization"
  | "Bound"
  | "Prediction"
  | "Experiment"
  | "Control"
  | "Portfolio";

interface BreakthroughSource {
  title: string;
  url: string;
}

export interface Breakthrough {
  date: string;
  displayDate: string;
  title: string;
  field: string;
  kind: BreakthroughKind;
  result: string;
  context: string;
  verificationLevel: string;
  aiRole: string;
  sourceTitle: string;
  sourceUrl: string;
  additionalSources?: BreakthroughSource[];
}

export const breakthroughs: Breakthrough[] = [
  {
    date: "2026-09-04",
    displayDate: "04 Sep 2026",
    title: "Fermat's Last Theorem became computer-checkable",
    field: "Number theory",
    kind: "Formalization",
    result: "Anthropic reports that Claude completed an end-to-end Lean formalization in 11 days, producing 13 million lines of code and about 29,500 intermediate theorems.",
    context: "Wiles proved the theorem in 1995. This formalizes the existing mathematical argument, building on Mathlib and community work led by Kevin Buzzard. The released artifact reports Lean kernel, comparator and independent-kernel checks; we have not rerun those resource-intensive checks.",
    verificationLevel: "Published proof artifact with reported kernel and comparator checks",
    aiRole: "Largely autonomous formalization with human orchestration and review",
    sourceTitle: "Formalizing Fermat's Last Theorem",
    sourceUrl: "https://www.anthropic.com/research/formalizing-fermats-last-theorem",
    additionalSources: [
      { title: "Complete Lean proof and verification instructions", url: "https://github.com/anthropics/fermats-last-theorem" },
      { title: "Original announcement on X", url: "https://x.com/AnthropicAI/status/2095947707605266436" },
    ],
  },
  {
    date: "2026-09-03",
    displayDate: "03 Sep 2026",
    title: "ARC-AGI-3 reached 99.9%",
    field: "General reasoning",
    kind: "Benchmark",
    result: "GPT-6 Astra scored 99.9% on the semi-private set with ARC Prize's Provider Adapter harness.",
    context: "The provider-neutral Standard harness scored 62.7%. ARC Prize explicitly says saturation is not proof of AGI, but it does mark the benchmark as a rapidly moving target.",
    verificationLevel: "Official benchmark evaluation",
    aiRole: "Autonomous task execution in two evaluation harnesses",
    sourceTitle: "OpenAI's GPT-6 Astra on ARC-AGI-3",
    sourceUrl: "https://arcprize.org/blog/astra",
  },
  {
    date: "2026-09-04",
    displayDate: "04 Sep 2026",
    title: "The prime-gap bound fell to 186",
    field: "Number theory",
    kind: "Bound",
    result: "Astra helped improve the unconditional result on bounded gaps between consecutive primes from 240 to 186, with a conditional Lean development and reproducible numerical certificate.",
    context: "This means infinitely many consecutive prime pairs differ by at most 186. Three high-level analytic and numerical inputs remain explicit Lean axioms, and this does not prove the twin-prime conjecture, where the target gap is 2.",
    verificationLevel: "Conditional formalization and reproducible certificate",
    aiRole: "Human-directed proof search, computation and formalization",
    sourceTitle: "GPT-6 Astra: short prime gaps",
    sourceUrl: "https://openai.com/index/gpt-6-astra/",
    additionalSources: [{
      title: "PrimeGaps186 proof repository",
      url: "https://github.com/openai/PrimeGaps186",
    }],
  },
  {
    date: "2026-07-27",
    displayDate: "27 Jul 2026",
    title: "A neurosurgeon entered the Crouzeix problem",
    field: "Operator theory",
    kind: "Proof",
    result: "Neurosurgery resident Jin Shanmu reported using a 16-hour agent run to produce a proof of Crouzeix's conjecture; an independent paper now proves the same conjecture and cites Jin's manuscript.",
    context: "Townsend, Greenbaum and Crouzeix checked Jin's manuscript, and an independent proof followed on 4 August. The exact autonomy story is author-reported rather than established by peer review.",
    verificationLevel: "Expert checked, then independently proved",
    aiRole: "A reported 16-hour unattended research run",
    sourceTitle: "SIAM News account by Townsend and Greenbaum",
    sourceUrl: "https://alextownsend.net/essays/SIAMNews_CrouzeixConjecture.pdf",
    additionalSources: [{
      title: "Independent proof of Crouzeix's conjecture",
      url: "https://arxiv.org/abs/2608.03841",
    }],
  },
  {
    date: "2026-08-01",
    displayDate: "01 Aug 2026",
    title: "Ten advances crossed into active mathematics",
    field: "Mathematics and theoretical CS",
    kind: "Portfolio",
    result: "Astra produced ten announced results spanning sphere packing, codes, non-sofic groups, rigidity, circuit lower bounds, quantum information, lattice hardness, Ehrhart theory, Ramsey theory and extremal graphs.",
    context: "The release says these results either resolve problems or make substantial progress. Lean checks encoded statements, while significance and statement-to-conjecture fidelity still require field review.",
    verificationLevel: "Announced portfolio with Lean certificates",
    aiRole: "Automated theorem proving and mathematical search",
    sourceTitle: "Ten advances in mathematics and theoretical computer science",
    sourceUrl: "https://openai.com/index/ten-advances-in-mathematics/",
    additionalSources: [{
      title: "Lean certificates for the ten results",
      url: "https://github.com/openai/ten-proofs",
    }],
  },
  {
    date: "2026-07-22",
    displayDate: "22 Jul 2026",
    title: "Dinitz-Garg-Goemans was disproved",
    field: "Combinatorial optimization",
    kind: "Counterexample",
    result: "Dmitry Rybin reported a concrete counterexample to a roughly 30-year-old conjecture about unsplittable flow, found in one model session.",
    context: "An independent exact-rational replication confirmed the finite instance forces a 16/15 demand blow-up. The broader cost-preserving O(d_max) rounding question remains open.",
    verificationLevel: "Exact finite certificate independently reproduced",
    aiRole: "One-session counterexample search",
    sourceTitle: "Dmitry Rybin's counterexample and transcript",
    sourceUrl: "https://x.com/DmitryRybin1/status/2079904005652893709",
    additionalSources: [{
      title: "Independent exact-rational verification",
      url: "https://zenodo.org/records/21554259",
    }],
  },
  {
    date: "2026-05-20",
    displayDate: "20 May 2026",
    title: "An Erdős unit-distance conjecture fell",
    field: "Discrete geometry",
    kind: "Counterexample",
    result: "An OpenAI research model constructed infinitely many point sets with at least n^(1+δ) unit-distance pairs for a fixed δ > 0.",
    context: "External mathematicians checked the proof. A later refinement by Will Sawin made the exponent explicit with δ = 0.014.",
    verificationLevel: "Externally checked proof and later refinement",
    aiRole: "Agent-generated construction with human verification",
    sourceTitle: "An OpenAI model disproved a central conjecture in discrete geometry",
    sourceUrl: "https://openai.com/index/model-disproves-discrete-geometry-conjecture/",
  },
  {
    date: "2026-05-01",
    displayDate: "01 May 2026",
    title: "A non-mathematician surfaced a 1966 proof route",
    field: "Analytic number theory",
    kind: "Proof",
    result: "A prompt from 23-year-old non-specialist Liam Price surfaced a von Mangoldt weighted Markov-chain idea that Price, Tao, Lichtman and five coauthors developed into proofs of Erdős problems 1196 and 1217.",
    context: "This was not a one-shot autonomous proof. The raw output needed expert interpretation and the eight-author paper substantially developed and generalized the method.",
    verificationLevel: "Public research preprint with expert development",
    aiRole: "Idea generation followed by an eight-author proof",
    sourceTitle: "Primitive sets and von Mangoldt chains",
    sourceUrl: "https://arxiv.org/abs/2605.00301",
  },
  {
    date: "2026-04-28",
    displayDate: "28 Apr 2026",
    title: "QED produced three original proofs",
    field: "Applied analysis and PDEs",
    kind: "Proof",
    result: "The QED system solved three of five expert-contributed open problems in its initial evaluation.",
    context: "The contributing domain experts judged all three proofs correct, original and nontrivial. The paper is a preprint and the initial sample is small.",
    verificationLevel: "Expert-checked preprint evaluation",
    aiRole: "Fully automated proof generation",
    sourceTitle: "QED: Generating mathematical proofs on open problems",
    sourceUrl: "https://arxiv.org/abs/2604.24021",
  },
  {
    date: "2026-02-06",
    displayDate: "06 Feb 2026",
    title: "A 700-problem sweep found four candidate advances",
    field: "Combinatorics and number theory",
    kind: "Proof",
    result: "Aletheia screened 700 Erdős database entries. Human review classified two outputs as full resolutions, two as partial resolutions, four as independent rediscoveries and five as literature matches.",
    context: "Only 13 of 200 definitively graded candidates were meaningful, and none of the four potentially novel items individually reached paper level. This is a warning that novelty review matters as much as proof checking.",
    verificationLevel: "Human-reviewed preprint evaluation",
    aiRole: "Semi-autonomous screening and proof attempts",
    sourceTitle: "Semi-Autonomous Mathematics Discovery with Gemini",
    sourceUrl: "https://arxiv.org/abs/2601.22401",
  },
  {
    date: "2025-09-18",
    displayDate: "18 Sep 2025",
    title: "New unstable fluid singularities were computed",
    field: "Fluid dynamics",
    kind: "Construction",
    result: "Curated physics-informed neural networks and high-precision optimization found new families of unstable self-similar singularities for incompressible porous media and three-dimensional Euler flow with a boundary.",
    context: "These are high-precision numerical solutions suitable for later computer-assisted proof. They do not prove Navier-Stokes blow-up or boundary-free Euler singularity formation.",
    verificationLevel: "Numerical research preprint",
    aiRole: "Machine-assisted numerical discovery with expert curation",
    sourceTitle: "Discovery of unstable singularities",
    sourceUrl: "https://arxiv.org/abs/2509.14185",
  },
  {
    date: "2025-07-21",
    displayDate: "21 Jul 2025",
    title: "IMO gold arrived in natural language",
    field: "Olympiad mathematics",
    kind: "Benchmark",
    result: "An advanced Gemini Deep Think system earned 35 of 42 points on the 2025 International Mathematical Olympiad, reaching the gold-medal threshold.",
    context: "The model read and answered the official problems in natural language within the competition time limit. These were difficult new contest problems, not open research conjectures.",
    verificationLevel: "Official Olympiad grading",
    aiRole: "Natural-language contest problem solving",
    sourceTitle: "Gemini Deep Think achieves IMO gold-medal standard",
    sourceUrl: "https://deepmind.google/blog/advanced-version-of-gemini-with-deep-think-officially-achieves-gold-medal-standard-at-the-international-mathematical-olympiad/",
  },
  {
    date: "2025-05-14",
    displayDate: "14 May 2025",
    title: "AlphaEvolve improved 20% of its open-problem set",
    field: "Algorithmic mathematics",
    kind: "Algorithm",
    result: "Across more than 50 open problems, AlphaEvolve reported new best results in roughly one fifth, including 593 touching spheres in 11 dimensions.",
    context: "It also found a 48-multiplication algorithm for 4x4 complex matrices. These are evaluator-friendly constructions, not general natural-language theorem proofs.",
    verificationLevel: "Announced constructions with exact evaluators",
    aiRole: "Evolutionary code search",
    sourceTitle: "AlphaEvolve: designing advanced algorithms",
    sourceUrl: "https://deepmind.google/blog/alphaevolve-a-gemini-powered-coding-agent-for-designing-advanced-algorithms/",
  },
  {
    date: "2024-07-25",
    displayDate: "25 Jul 2024",
    title: "Formal theorem proving reached IMO silver",
    field: "Olympiad mathematics",
    kind: "Benchmark",
    result: "AlphaProof and AlphaGeometry 2 solved four of six 2024 IMO problems for 28 of 42 points, the equivalent of a silver medal.",
    context: "Experts first translated the statements into formal language, and some searches ran for days. The milestone showed the value of machine-checkable reasoning without removing the formulation bottleneck.",
    verificationLevel: "Official Olympiad grading",
    aiRole: "Formal proof search after human translation",
    sourceTitle: "AI solves IMO problems at silver-medal level",
    sourceUrl: "https://deepmind.google/discover/blog/ai-solves-imo-problems-at-silver-medal-level/",
  },
  {
    date: "2024-01-17",
    displayDate: "17 Jan 2024",
    title: "AlphaGeometry matched Olympiad specialists",
    field: "Euclidean geometry",
    kind: "Benchmark",
    result: "AlphaGeometry solved 25 of 30 historical Olympiad geometry problems, compared with 10 for the previous state of the art and 25.9 for the average gold medallist.",
    context: "The system combines a neural language model with symbolic deduction. Its proofs are checkable, but the domain is tightly formalized and the problems already had known solutions.",
    verificationLevel: "Published benchmark evaluation",
    aiRole: "Neuro-symbolic proof generation",
    sourceTitle: "An Olympiad-level system for geometry",
    sourceUrl: "https://deepmind.google/blog/alphageometry-an-olympiad-level-ai-system-for-geometry/",
  },
  {
    date: "2023-12-14",
    displayDate: "14 Dec 2023",
    title: "FunSearch found new cap sets",
    field: "Extremal combinatorics",
    kind: "Construction",
    result: "FunSearch produced previously unknown cap-set constructions and the largest improvement in 20 years to the asymptotic lower bound.",
    context: "The Nature paper also reports online bin-packing heuristics that beat established baselines. Executable evaluators discarded invalid candidates before they entered the search loop.",
    verificationLevel: "Peer reviewed with executable evaluation",
    aiRole: "Language-model-guided program search",
    sourceTitle: "Mathematical discoveries from program search",
    sourceUrl: "https://www.nature.com/articles/s41586-023-06924-6",
  },
  {
    date: "2023-11-29",
    displayDate: "29 Nov 2023",
    title: "An autonomous lab made 36 new compounds",
    field: "Materials science",
    kind: "Experiment",
    result: "A-Lab planned and executed solid-state synthesis experiments continuously for 17 days, realizing 36 of 57 computationally proposed inorganic compounds.",
    context: "Language models proposed recipes, active learning refined them, and robotics ran the experiments. This is a closed-loop laboratory result, not evidence that autonomous systems can conduct every kind of experiment.",
    verificationLevel: "Peer reviewed and experimentally realized",
    aiRole: "Closed-loop planning, active learning and robotics",
    sourceTitle: "An autonomous laboratory for accelerated materials synthesis",
    sourceUrl: "https://www.nature.com/articles/s41586-023-06734-w",
  },
  {
    date: "2023-11-29",
    displayDate: "29 Nov 2023",
    title: "GNoME expanded the stable-crystal catalogue",
    field: "Materials science",
    kind: "Prediction",
    result: "Graph networks identified 2.2 million candidate stable crystal structures, including 381,000 entries on the updated convex hull; 736 matched structures independently realized experimentally.",
    context: "Computational stability is not the same as successful synthesis or a useful material. The result radically expanded the search space and supplied experimentally grounded validation for a subset.",
    verificationLevel: "Peer reviewed with experimental matches",
    aiRole: "Large-scale predictive materials search",
    sourceTitle: "Scaling deep learning for materials discovery",
    sourceUrl: "https://www.nature.com/articles/s41586-023-06735-9",
  },
  {
    date: "2023-06-07",
    displayDate: "07 Jun 2023",
    title: "AlphaDev rewrote a standard sorting primitive",
    field: "Computer science",
    kind: "Algorithm",
    result: "AlphaDev discovered shorter, lower-latency sorting routines that were incorporated into the LLVM standard C++ library.",
    context: "The gains concern small sorting routines at assembly level, where correctness and latency can be measured exactly. They do not replace general-purpose sorting theory.",
    verificationLevel: "Peer reviewed and deployed in LLVM",
    aiRole: "Reinforcement-learning algorithm discovery",
    sourceTitle: "Faster sorting algorithms discovered using deep reinforcement learning",
    sourceUrl: "https://www.nature.com/articles/s41586-023-06004-9",
  },
  {
    date: "2022-10-05",
    displayDate: "05 Oct 2022",
    title: "AlphaTensor broke matrix-multiplication records",
    field: "Computational algebra",
    kind: "Algorithm",
    result: "AlphaTensor found exact matrix-multiplication algorithms that improved the best-known multiplication counts for several matrix sizes, including 4x4 matrices over a finite field.",
    context: "Each candidate could be verified mechanically. The result established an early pattern: frontier discovery accelerates when a problem can be expressed as a search space with an exact evaluator.",
    verificationLevel: "Peer reviewed and mechanically checked",
    aiRole: "Reinforcement-learning algorithm discovery",
    sourceTitle: "Discovering faster matrix multiplication algorithms",
    sourceUrl: "https://www.nature.com/articles/s41586-022-05172-4",
  },
  {
    date: "2022-02-16",
    displayDate: "16 Feb 2022",
    title: "A learned controller held new plasma shapes",
    field: "Fusion physics",
    kind: "Control",
    result: "A deep-reinforcement-learning controller operated all 19 magnetic coils on the TCV tokamak and sustained configurations including two separate plasma droplets.",
    context: "This solved a difficult real-time control task and reduced controller-design effort. It did not solve net-positive fusion energy or the broader confinement problem.",
    verificationLevel: "Peer reviewed and tested on tokamak hardware",
    aiRole: "Learned real-time control",
    sourceTitle: "Magnetic control of tokamak plasmas through deep reinforcement learning",
    sourceUrl: "https://www.nature.com/articles/s41586-021-04301-9",
  },
  {
    date: "2021-12-01",
    displayDate: "01 Dec 2021",
    title: "Models helped mathematicians form new conjectures",
    field: "Topology and representation theory",
    kind: "Proof",
    result: "Machine-learning attribution guided mathematicians to a new relationship between algebraic and geometric knot invariants and to a conjectural route for a combinatorial invariance problem.",
    context: "The systems exposed patterns and useful variables; mathematicians iteratively interpreted them, formed conjectures and supplied the proofs. This was human-machine research, not autonomous theorem proving.",
    verificationLevel: "Peer reviewed with human proofs",
    aiRole: "Guided conjecture formation and mathematical intuition",
    sourceTitle: "Advancing mathematics by guiding human intuition with AI",
    sourceUrl: "https://www.nature.com/articles/s41586-021-04086-x",
  },
  {
    date: "2021-07-15",
    displayDate: "15 Jul 2021",
    title: "AlphaFold reached near-experimental structure accuracy",
    field: "Structural biology",
    kind: "Prediction",
    result: "AlphaFold became the first computational method to predict protein structures to near-experimental accuracy in a majority of the CASP14 targets.",
    context: "It transformed structure prediction from amino-acid sequence. It does not fully solve protein dynamics, interactions, folding pathways or every protein structure.",
    verificationLevel: "Peer reviewed and blind benchmarked",
    aiRole: "Deep-learning structure prediction",
    sourceTitle: "Highly accurate protein structure prediction with AlphaFold",
    sourceUrl: "https://www.nature.com/articles/s41586-021-03819-2",
  },
  {
    date: "2020-02-20",
    displayDate: "20 Feb 2020",
    title: "A model repurposed halicin as an antibiotic lead",
    field: "Drug discovery",
    kind: "Experiment",
    result: "A neural model surfaced halicin from a repurposing library; laboratory tests showed broad-spectrum antibacterial activity and efficacy in mouse infection models.",
    context: "This was a validated lead-discovery result, not an approved medicine. Safety, dosing, resistance and clinical efficacy still required the normal development process.",
    verificationLevel: "Peer reviewed and laboratory validated",
    aiRole: "Predictive screening followed by experiments",
    sourceTitle: "A deep learning approach to antibiotic discovery",
    sourceUrl: "https://www.cell.com/cell/fulltext/S0092-8674(20)30102-1",
  },
];
