import type { OpenProblem } from "@/lib/types";

type ResearchProblem = Omit<OpenProblem, "starterPrompt" | "verified" | "agentReadiness" | "executionResources">;

function researchProblem(problem: ResearchProblem): OpenProblem {
  return {
    ...problem,
    verified: "2026-09-06",
    agentReadiness: "agent-ready",
    executionResources: "A local computer and the cited literature are sufficient for the first step. Larger exhaustive searches may require additional compute.",
    starterPrompt: `Investigate ${problem.title}. First check the current status of the exact statement against primary literature, including corrections and recent solution claims. The research question is: ${problem.statement}\n\nBegin with this bounded task: ${problem.smallestStep}\n\nSuccess for this first task means: ${problem.successCriterion}\n\nUse exact arithmetic or independently checkable proof certificates where applicable. State every assumption and search bound. Separate proved statements, numerical observations and conjectures. Compare any proposed result with the literature before calling it new. Return reproducible artifacts and an honest account of what remains unresolved.`,
  };
}

export const additionalMathsProblems: OpenProblem[] = [
  researchProblem({
    id: "twin-primes",
    title: "Twin prime conjecture",
    field: "Mathematics",
    subfield: "Number theory",
    summary: "Are there infinitely many pairs of primes separated by two?",
    statement: "Are there infinitely many primes p such that p + 2 is also prime?",
    whyOpen: "Bounded-gap theorems guarantee infinitely many close prime pairs, but do not force the gap to equal two. The parity barrier explains why the established sieve methods alone do not reach this conclusion.",
    smallestStep: "Reproduce one finite-dimensional sieve optimization from the Polymath bounded-gap paper using rational arithmetic, and identify exactly where the argument stops distinguishing primes from almost primes.",
    successCriterion: "An independently checked optimization certificate and a precise account of which additional estimate would improve its conclusion.",
    agentFit: 46,
    scale: "monument",
    introduced: 1849,
    location: { name: "Paris, France (de Polignac's conjecture)", longitude: 2.3522, latitude: 48.8566 },
    tags: ["primes", "sieve methods", "certified bounds"],
    tools: ["SageMath", "rational optimization", "Lean"],
    sources: [
      { title: "Variants of the Selberg sieve, and bounded intervals containing many primes", url: "https://arxiv.org/abs/1407.4897", kind: "primary", passage: "We modify the \"parity problem\" argument of Selberg", publishedAt: "2014-12-22" },
      { title: "Weakening the Legendre Conjecture", url: "https://arxiv.org/html/2602.22502v1", kind: "survey", publishedAt: "2026-02-25" },
    ],
  }),
  researchProblem({
    id: "legendre-primes",
    title: "Primes between consecutive squares",
    field: "Mathematics",
    subfield: "Number theory",
    summary: "Is there always a prime between n² and the next square?",
    statement: "For every integer n ≥ 1, does a prime p exist with n² < p < (n + 1)²?",
    whyOpen: "Results for wider intervals and for numbers with several prime factors do not establish a prime in every square interval. Even assuming the Riemann hypothesis does not settle this exact statement.",
    smallestStep: "Reproduce the explicit sieve inequalities in the four-prime-factor result, with interval bounds on numerical constants, and test whether one estimate can be sharpened.",
    successCriterion: "A reproducible certificate for a published explicit bound, or a rigorously improved bound with all finite checks recorded.",
    agentFit: 62,
    scale: "frontier",
    location: { name: "Canberra, Australia (Johnston's explicit sieve research)", longitude: 149.13, latitude: -35.28 },
    tags: ["prime gaps", "explicit estimates", "sieves"],
    tools: ["Arb", "SageMath", "interval arithmetic"],
    sources: [
      { title: "Almost primes between all squares", url: "https://arxiv.org/html/2501.18048", kind: "primary", passage: "Even under the Riemann hypothesis, Legendre’s conjecture is still open" },
      { title: "Weakening the Legendre Conjecture", url: "https://arxiv.org/html/2602.22502v1", kind: "survey", publishedAt: "2026-02-25" },
    ],
  }),
  researchProblem({
    id: "perfect-cuboid",
    title: "Perfect cuboid",
    field: "Mathematics",
    subfield: "Diophantine equations",
    summary: "Can a rectangular box have integer edges, face diagonals and space diagonal?",
    statement: "Do positive integers a, b, c exist such that a² + b², a² + c², b² + c² and a² + b² + c² are all squares?",
    whyOpen: "Boxes with integer face diagonals are known, but no nondegenerate box satisfying all four square conditions is established. Geometric descriptions and bounded searches do not classify all rational points on the associated surface.",
    smallestStep: "Implement the four equations with exact integers, reproduce the exclusion of one published parameterized family, and certify a bounded search after symmetry and congruence reductions.",
    successCriterion: "A checked family-exclusion lemma or a complete finite-search certificate with explicit bounds and independently verified candidate tests.",
    agentFit: 81,
    scale: "foothold",
    location: { name: "Bayreuth, Germany (Stoll's cuboid-surface research)", longitude: 11.5789, latitude: 49.9456 },
    tags: ["integer geometry", "rational points", "exact search"],
    tools: ["SageMath", "PARI/GP", "Lean"],
    sources: [
      { title: "The surface parametrizing cuboids", url: "https://arxiv.org/html/1009.0388", kind: "primary", passage: "It is an open problem whether a ‘rational box’ exists" },
      { title: "The L-function of the surface parametrizing cuboids", url: "https://arxiv.org/pdf/2512.22520", kind: "primary" },
      { title: "Treasure Hunting Perfect Euler bricks", url: "https://people.math.harvard.edu/~knill/various/eulercuboid/lecture.pdf", kind: "survey" },
    ],
  }),
  researchProblem({
    id: "union-closed-sets",
    title: "Union-closed sets conjecture",
    field: "Mathematics",
    subfield: "Extremal combinatorics",
    summary: "Must some element appear in at least half the sets of a union-closed family?",
    statement: "For every finite nonempty family F of finite sets with nonempty union, if A ∪ B belongs to F whenever A and B belong to F, must some element occur in at least |F|/2 members?",
    whyOpen: "Entropy methods prove a positive universal frequency, and structural arguments settle special families. The required frequency of one half remains beyond the general results.",
    smallestStep: "Enumerate union-closed families on a small ground set up to relabeling, compute element frequencies exactly, and test a precisely stated extra hypothesis suggested by extremal examples.",
    successCriterion: "A complete classification for the declared finite domain, followed by either a checked special-case lemma or an explicit counterexample to the proposed strengthening.",
    agentFit: 84,
    scale: "foothold",
    introduced: 1979,
    location: { name: "Taipei, Taiwan (Das and Wu's frequency bounds)", longitude: 121.5654, latitude: 25.033 },
    tags: ["set families", "entropy", "finite enumeration"],
    tools: ["SAT", "SageMath", "Lean"],
    sources: [
      { title: "A constant lower bound for the union-closed sets conjecture", url: "https://arxiv.org/abs/2211.09055", kind: "primary" },
      { title: "Frequent elements in union-closed set families", url: "https://arxiv.org/html/2412.03862", kind: "primary", passage: "The problem has stubbornly resisted all attacks, with only partial results having been obtained to date." },
      { title: "On the lattice formulation of the union-closed sets conjecture", url: "https://arxiv.org/abs/2503.00277", kind: "primary", publishedAt: "2025-03-01" },
    ],
  }),
  researchProblem({
    id: "graceful-trees",
    title: "Graceful tree conjecture",
    field: "Mathematics",
    subfield: "Graph theory",
    summary: "Can every tree be numbered so that its edge differences are all distinct?",
    statement: "For every tree T with n vertices, is there a bijection f: V(T) → {0, …, n − 1} whose absolute differences |f(u) − f(v)| over edges uv are exactly {1, …, n − 1}?",
    whyOpen: "Many tree families admit explicit labelings, and recent work obtains asymptotically almost all distinct differences. Almost graceful does not imply an exact labeling for every tree.",
    smallestStep: "Build a certificate-producing labeling solver, validate it on paths and caterpillars, then study one family outside the hypotheses of the cited spider results.",
    successCriterion: "Checked labelings for a declared family and a symbolic construction or minimal obstruction to a proposed extension rule.",
    agentFit: 88,
    scale: "foothold",
    introduced: 1967,
    location: { name: "London, United Kingdom (UCL gracesize research)", longitude: -0.1276, latitude: 51.5072 },
    tags: ["graph labeling", "trees", "constraint solving"],
    tools: ["CP-SAT", "nauty", "Lean"],
    sources: [
      { title: "On the gracesize of trees", url: "https://arxiv.org/abs/2511.11331", kind: "primary", passage: "every sufficiently large tree admits an almost graceful labelling", publishedAt: "2026-07-31" },
      { title: "Graceful Labeling of Two Families of Spiders", url: "https://arxiv.org/abs/2605.14295", kind: "primary", publishedAt: "2026-05-15" },
    ],
  }),
  researchProblem({
    id: "ramsey-five-five",
    title: "The exact value of R(5,5)",
    field: "Mathematics",
    subfield: "Ramsey theory",
    summary: "How many vertices force a five-vertex clique or independent set?",
    statement: "Determine the smallest n such that every simple graph on n vertices contains either five pairwise adjacent vertices or five pairwise nonadjacent vertices.",
    whyOpen: "The cited computer-assisted result proves the upper bound 46, while a 42-vertex construction gives the lower bound 43. These bounds do not determine the exact value.",
    smallestStep: "Reproduce a known 42-vertex witness and a small case of the upper-bound computation; then select a symmetry-restricted 43-vertex search with independently checkable certificates.",
    successCriterion: "A verified witness or an exhaustive exclusion for the explicitly declared symmetry class, with no claim about omitted graphs.",
    agentFit: 87,
    scale: "foothold",
    location: { name: "Canberra, Australia (Angeltveit and McKay's bound)", longitude: 149.13, latitude: -35.28 },
    tags: ["Ramsey numbers", "SAT", "proof certificates"],
    tools: ["nauty", "SAT", "linear programming"],
    sources: [
      { title: "R(5,5) ≤ 46", url: "https://arxiv.org/abs/2409.15709", kind: "primary", passage: "All of the computations were independently implemented by both authors, with consistent results.", publishedAt: "2025-09-01" },
      { title: "R(5,5) ≤ 46, Journal of Graph Theory", url: "https://onlinelibrary.wiley.com/doi/10.1002/jgt.70029", kind: "primary", doi: "10.1002/jgt.70029" },
    ],
  }),
  researchProblem({
    id: "hodge-conjecture",
    title: "Hodge conjecture",
    field: "Mathematics",
    subfield: "Algebraic geometry",
    summary: "Do the topological features identified by Hodge theory always come from algebraic pieces?",
    statement: "For every smooth complex projective variety X and integer p ≥ 0, is every class in H^{2p}(X,Q) ∩ H^{p,p}(X) a rational linear combination of classes of codimension-p algebraic subvarieties? Here H^{p,p} denotes the (p,p) component of the Hodge decomposition.",
    whyOpen: "The conjecture requires constructing algebraic cycles from cohomological information. Results for divisors and special varieties do not supply such cycles in all higher codimensions.",
    smallestStep: "Choose a smooth projective variety with a published cycle calculation, reproduce its cohomology dimensions and intersection matrix exactly, and isolate one dependency suitable for formal proof.",
    successCriterion: "A checked calculation for the chosen variety and a precisely scoped formal lemma, without extrapolating to arbitrary varieties.",
    agentFit: 28,
    scale: "monument",
    location: { name: "Cambridge, United Kingdom (Hodge's research base)", longitude: 0.1218, latitude: 52.2053 },
    tags: ["algebraic cycles", "cohomology", "Clay Prize"],
    tools: ["Macaulay2", "SageMath", "Lean"],
    sources: [
      { title: "Hodge Conjecture, Clay Mathematics Institute", url: "https://www.claymath.org/millennium/hodge-conjecture/", kind: "primary", passage: "the pieces called Hodge cycles are actually (rational linear) combinations of geometric pieces called algebraic cycles" },
    ],
  }),
  researchProblem({
    id: "hadwiger-graph-minors",
    title: "Hadwiger's graph coloring conjecture",
    field: "Mathematics",
    subfield: "Graph theory",
    summary: "Must a graph needing k colors contain a complete k-vertex graph as a minor?",
    statement: "Does every finite simple graph G with chromatic number k contain Kₖ as a minor, obtained by deleting vertices or edges and contracting edges?",
    whyOpen: "Known small cases and asymptotic coloring bounds do not prove the exact relationship for arbitrary k. Current work still restricts the structure of a possible minimal counterexample.",
    smallestStep: "Encode color-critical graphs and clique-minor witnesses for a small restricted class, then test one connectivity reduction from the current minimal-counterexample literature.",
    successCriterion: "An independently checked minor witness or a formally justified reduction for the declared graph class.",
    agentFit: 69,
    scale: "frontier",
    introduced: 1943,
    location: { name: "Bern, Switzerland (Hadwiger's research base)", longitude: 7.4474, latitude: 46.948 },
    tags: ["graph coloring", "minors", "structural graph theory"],
    tools: ["SageMath", "SAT", "Lean"],
    sources: [
      { title: "Connectivities for k-knitted graphs and for minimal counterexamples to Hadwiger's Conjecture", url: "https://arxiv.org/abs/2606.01586", kind: "primary", publishedAt: "2026-06-04" },
      { title: "Hadwiger's conjecture for hypergraphs", url: "https://arxiv.org/abs/2607.27243", kind: "primary", publishedAt: "2026-08-13" },
    ],
  }),
  researchProblem({
    id: "graph-reconstruction",
    title: "Graph reconstruction conjecture",
    field: "Mathematics",
    subfield: "Graph theory",
    summary: "Can a graph always be recovered from all its vertex-deleted views?",
    statement: "Are any two finite simple graphs on at least three vertices isomorphic whenever their multisets of unlabeled vertex-deleted subgraphs are equal?",
    whyOpen: "Many invariants and graph classes are reconstructible, including interval graphs in recent work. These results do not prove that every deck identifies a unique graph.",
    smallestStep: "Build a canonical deck calculator for small graphs, reproduce reconstruction of edge counts and degree sequences, and test a specific proposed deck invariant on all graphs within a declared order bound.",
    successCriterion: "An exhaustively checked invariant implication or a pair of explicit graphs disproving the proposed implication.",
    agentFit: 86,
    scale: "foothold",
    location: { name: "York, United Kingdom (Dufresne's invariant-theory research)", longitude: -1.0827, latitude: 53.9583 },
    tags: ["graph invariants", "reconstruction", "exact enumeration"],
    tools: ["nauty", "SageMath", "Lean"],
    sources: [
      { title: "Shuffling the Deck: Invariant Theory and the Graph Reconstruction Conjecture", url: "https://arxiv.org/abs/2604.16567", kind: "survey", publishedAt: "2026-04-17" },
      { title: "Interval Graphs are Reconstructible", url: "https://arxiv.org/abs/2504.02353", kind: "primary", publishedAt: "2026-05-12" },
    ],
  }),
  researchProblem({
    id: "sidorenko",
    title: "Sidorenko's conjecture",
    field: "Mathematics",
    subfield: "Extremal graph theory",
    summary: "Does a random graph minimize every bipartite pattern at a fixed edge density?",
    statement: "For every finite bipartite graph H and every nonempty finite simple graph G, is t(H,G) ≥ t(K₂,G)^|E(H)|, where t(H,G) counts all edge-preserving vertex maps divided by |V(G)|^|V(H)|?",
    whyOpen: "The inequality holds for many bipartite patterns, but no argument covers all of them. Recent symmetry and spectral reductions still leave a universal inequality to prove.",
    smallestStep: "Choose one bipartite pattern not covered by the cited closure rules, optimize its density on rational step-function graph models, and try to turn the resulting inequality into an exact sum-of-squares certificate.",
    successCriterion: "A rational certificate for the declared model family, or a rigorously validated counterexample to a proposed stronger inequality.",
    agentFit: 77,
    scale: "frontier",
    location: { name: "Budapest, Hungary (the Erdős-Simonovits formulation)", longitude: 19.0402, latitude: 47.4979 },
    tags: ["graph densities", "inequalities", "sum of squares"],
    tools: ["SDP", "SageMath", "rational certificates"],
    sources: [
      { title: "Conjugacy Class Averages and Sidorenko's Conjecture", url: "https://arxiv.org/abs/2606.15368", kind: "primary", publishedAt: "2026-06-13" },
      { title: "Spectral Sidorenko inequalities and edge-spectral supersaturation", url: "https://arxiv.org/abs/2605.26614", kind: "primary", publishedAt: "2026-06-03" },
    ],
  }),
  researchProblem({
    id: "erdos-hajnal",
    title: "Erdős-Hajnal conjecture",
    field: "Mathematics",
    subfield: "Extremal graph theory",
    summary: "Does forbidding one induced pattern force a much larger clique or independent set?",
    statement: "For every finite graph H, does there exist ε(H) > 0 such that every n-vertex graph with no induced copy of H has a clique or independent set of size at least n^ε(H)?",
    whyOpen: "The general conjecture remains open despite recent progress on small forbidden graphs. Verifying finitely many graph sizes cannot establish the polynomial-size guarantee for all n.",
    smallestStep: "Use the current list of settled forbidden patterns to select an unresolved case, then enumerate small H-free graphs and test one structural lemma required by an iterative sparsification approach.",
    successCriterion: "A precisely stated lemma with a proof in the restricted case, or a certified minimal counterexample showing why that lemma needs revision.",
    agentFit: 71,
    scale: "frontier",
    introduced: 1989,
    location: { name: "Tianjin, China (Nankai's six-vertex research)", longitude: 117.2, latitude: 39.1333 },
    tags: ["induced subgraphs", "Ramsey theory", "structural lemmas"],
    tools: ["nauty", "SAT", "Lean"],
    sources: [
      { title: "Erdős-Hajnal conjecture beyond five-vertex graphs", url: "https://arxiv.org/abs/2606.06258", kind: "primary", passage: "This conjecture, known as the Erdős-Hajnal conjecture, is a central open problem in combinatorics", publishedAt: "2026-08-31" },
    ],
  }),
  researchProblem({
    id: "cerny-reset-words",
    title: "Černý's reset-word conjecture",
    field: "Computer science",
    subfield: "Automata theory",
    summary: "How long a word is needed to send every state of a machine to the same state?",
    statement: "Does every synchronizing complete deterministic finite automaton with n ≥ 2 states admit a reset word of length at most (n − 1)²? A reset word sends every starting state to a single state.",
    whyOpen: "The bound is attained by a known family and proved for many classes, but the general upper bounds and structural reductions do not establish it for every synchronizing automaton.",
    smallestStep: "Implement exact shortest-reset-word search on the subset automaton, reproduce the Černý family, and test one unresolved subclass identified in Volkov's survey.",
    successCriterion: "Checked shortest-word certificates for a declared finite class and either a proved extension lemma or an explicit obstruction to it.",
    agentFit: 90,
    scale: "foothold",
    introduced: 1964,
    location: { name: "Milan, Italy (Rodaro and Venturi's automata research)", longitude: 9.19, latitude: 45.4642 },
    tags: ["automata", "synchronization", "shortest paths"],
    tools: ["Rust", "SAT", "Lean"],
    sources: [
      { title: "List of Results on the Černý Conjecture and Reset Thresholds for Synchronizing Automata", url: "https://arxiv.org/abs/2508.15655", kind: "survey", publishedAt: "2026-01-13" },
      { title: "The hereditariness problem for the Černý conjecture", url: "https://arxiv.org/abs/2509.17992", kind: "primary", publishedAt: "2026-02-10" },
    ],
  }),
  researchProblem({
    id: "log-rank",
    title: "Log-rank conjecture",
    field: "Computer science",
    subfield: "Communication complexity",
    summary: "Does the rank of a Boolean matrix control how much two people must communicate?",
    statement: "Is there a universal constant C such that every Boolean communication matrix M satisfies D(M) ≤ O((1 + log₂ rankℝ(M))^C), where D is deterministic two-party communication complexity? Treat the all-zero matrix separately.",
    whyOpen: "General upper bounds grow much faster than a polynomial in log rank. Recent equivalent formulations reduce the question to decompositions of matrices, but do not prove the required bound.",
    smallestStep: "For a small family of Boolean matrices, compute exact real rank and minimum monochromatic rectangle partitions; reproduce a known separation before testing a restricted decomposition lemma.",
    successCriterion: "An exact partition certificate and a verified rank calculation, plus a proved restricted lemma or explicit counterexample to it.",
    agentFit: 68,
    scale: "frontier",
    introduced: 1988,
    location: { name: "Victoria, Canada (Hambardzumyan and Shirley's formulations)", longitude: -123.3656, latitude: 48.4284 },
    tags: ["communication complexity", "matrix rank", "rectangle partitions"],
    tools: ["ILP", "SageMath", "Lean"],
    sources: [
      { title: "The Log-Rank Conjecture: New Equivalent Formulations", url: "https://arxiv.org/abs/2510.02583", kind: "primary", passage: "The log-rank conjecture is a longstanding open problem", publishedAt: "2026-08-14" },
    ],
  }),
  researchProblem({
    id: "signed-rectangle-rank",
    title: "A linear bound for signed rectangle decompositions",
    field: "Computer science",
    subfield: "Algebraic complexity",
    summary: "Can every Boolean matrix be built from only a constant times its rank many signed rectangles?",
    statement: "Is there an absolute constant C such that every Boolean matrix M can be expressed as a sum of at most C rankℝ(M) all-one rectangle indicator matrices, each with coefficient +1 or −1?",
    whyOpen: "The cited paper proves an O(r log r) upper bound and explicitly asks whether the logarithm can be removed. This narrower question does not itself settle the full log-rank conjecture.",
    smallestStep: "Enumerate small Boolean matrices up to row and column permutations, solve their signed rectangle decompositions exactly, and search for a family with a growing ratio to real rank.",
    successCriterion: "Certified optimal decompositions or lower bounds for the tested matrices, followed by a symbolic bound for one infinite family if the evidence supports it.",
    agentFit: 87,
    scale: "foothold",
    introduced: 2025,
    location: { name: "San Diego, California (Lovett's matrix research)", longitude: -117.1611, latitude: 32.7157 },
    tags: ["Boolean matrices", "integer programming", "explicit open question"],
    tools: ["ILP", "SageMath", "proof certificates"],
    sources: [
      { title: "The Log-Rank Conjecture: New Equivalent Formulations, Question 1.5", url: "https://arxiv.org/html/2510.02583v3", kind: "primary", passage: "Is it true that for every Boolean matrix M, srr(M) ≤ O(r(M))?" },
    ],
  }),
  researchProblem({
    id: "polynomial-graph-isomorphism",
    title: "Polynomial-time graph isomorphism",
    field: "Computer science",
    subfield: "Algorithms",
    summary: "Can we always test efficiently whether two graphs differ only in their vertex names?",
    statement: "Is there a deterministic algorithm that decides isomorphism of every pair of finite simple n-vertex graphs in n^O(1) time?",
    whyOpen: "Quasipolynomial worst-case algorithms and efficient methods for typical or perturbed graphs leave the polynomial worst-case question unresolved. Strong performance on benchmarks does not establish that complexity bound.",
    smallestStep: "Reproduce color refinement on a published hard graph family and the cited perturbed-graph examples; isolate a structural parameter that explains the failure cases.",
    successCriterion: "A reproducible family of failures and a proved runtime or distinguishing guarantee under an explicit additional hypothesis.",
    agentFit: 74,
    scale: "frontier",
    location: { name: "Klosterneuburg, Austria (ISTA's smoothed-analysis research)", longitude: 16.3253, latitude: 48.3052 },
    tags: ["graph algorithms", "complexity", "color refinement"],
    tools: ["nauty", "SageMath", "Rust"],
    sources: [
      { title: "Smoothed analysis for graph isomorphism", url: "https://arxiv.org/abs/2410.06095", kind: "primary", passage: "There is no known polynomial-time algorithm for graph isomorphism testing", publishedAt: "2025-10-16" },
    ],
  }),
  researchProblem({
    id: "deterministic-pit",
    title: "Deterministic polynomial identity testing",
    field: "Computer science",
    subfield: "Algebraic algorithms",
    summary: "Can we test whether an arithmetic circuit computes zero without using randomness?",
    statement: "Over the rational numbers, can zero-polynomial identity testing for general arithmetic circuits of size s and degree d be done deterministically in time polynomial in s, d and the encoding length of constants?",
    whyOpen: "Random evaluations give efficient probabilistic tests. Deterministic hitting sets and algorithms cover restricted circuit models, but do not yet handle general circuits with the same efficiency.",
    smallestStep: "Reproduce the hitting-set construction for sums of high powers of sparse polynomials in the cited paper, then test which step fails when its degree restriction is relaxed.",
    successCriterion: "A verified hitting set for the stated restricted model, or a counterexample to an attempted extension with every parameter recorded.",
    agentFit: 78,
    scale: "frontier",
    location: { name: "Tel Aviv, Israel (Shpilka and Tal's circuit research)", longitude: 34.7818, latitude: 32.0853 },
    tags: ["derandomization", "arithmetic circuits", "hitting sets"],
    tools: ["SageMath", "symbolic algebra", "Lean"],
    sources: [
      { title: "Polynomial Identity Testing and Reconstruction for Depth-4 Powering Circuits of High Degree", url: "https://arxiv.org/abs/2602.20832", kind: "primary", publishedAt: "2026-02-24" },
      { title: "Efficient Polynomial Identity Testing Over Nonassociative Algebras", url: "https://arxiv.org/abs/2509.11349", kind: "primary", publishedAt: "2025-09-14" },
    ],
  }),
  researchProblem({
    id: "erdos-moser-equation",
    title: "Erdős-Moser equation",
    field: "Mathematics",
    subfield: "Diophantine equations",
    summary: "Can a sum of consecutive equal powers equal the next power, beyond 1 + 2 = 3?",
    statement: "Are m = 3 and k = 1 the only positive integer solution with m ≥ 2 and k ≥ 1 to 1ᵏ + 2ᵏ + ⋯ + (m − 1)ᵏ = mᵏ?",
    whyOpen: "Congruence arguments exclude odd exponents beyond the known solution and force any further solution to be enormous. They do not rule out all even exponents.",
    smallestStep: "Reproduce Moser's congruence restrictions using exact power sums and formalize one residue-class exclusion; then test whether combining a small set of moduli removes an additional class.",
    successCriterion: "A checked modular exclusion lemma and a complete account of the exponents and residues it covers.",
    agentFit: 82,
    scale: "foothold",
    introduced: 1953,
    location: { name: "Edmonton, Canada (Moser's research base)", longitude: -113.4938, latitude: 53.5461 },
    tags: ["power sums", "congruences", "formal proof"],
    tools: ["SageMath", "PARI/GP", "Lean"],
    sources: [
      { title: "Erdős-Moser Equation in Arithmetic Progressions", url: "https://arxiv.org/abs/2608.03375", kind: "primary", publishedAt: "2026-08-04" },
    ],
  }),
  researchProblem({
    id: "random-permanent-zero",
    title: "How often is a random permanent zero?",
    field: "Computer science",
    subfield: "Algebraic complexity",
    summary: "For a random square matrix over a fixed odd finite field, does its permanent vanish with probability approaching 1/q?",
    statement: "For each fixed odd prime power q and a uniformly random matrix A in Fq^(n×n), does Pr[per(A) = 0] → 1/q as n → ∞? The permanent sums products over permutations without determinant signs.",
    whyOpen: "The cited paper distinguishes permanental and ordinary rank for sufficiently thin rectangular matrices. It explicitly leaves the square-matrix zero probability unresolved.",
    smallestStep: "Compute exact permanent distributions for small n and q with a subset-dynamic-programming implementation, cross-check by direct permutation sums, and seek a recurrence for a restricted matrix family.",
    successCriterion: "Exact distributions with independent checks, and a proved recurrence or conditional bound for the stated restricted family.",
    agentFit: 89,
    scale: "foothold",
    location: { name: "Toronto, Canada (Ghasemi, Gross and Kopparty's research)", longitude: -79.3832, latitude: 43.6532 },
    tags: ["permanent", "finite fields", "random matrices"],
    tools: ["SageMath", "Rust", "exact enumeration"],
    sources: [
      { title: "Permanental rank versus determinantal rank of random matrices over finite fields", url: "https://arxiv.org/html/2512.03221v1", kind: "primary" },
    ],
  }),
  researchProblem({
    id: "quadratic-primes",
    title: "Infinitely many primes of the form n² + 1",
    field: "Mathematics",
    subfield: "Number theory",
    summary: "Does squaring an integer and adding one produce infinitely many primes?",
    statement: "Are there infinitely many positive integers n for which n² + 1 is prime?",
    whyOpen: "Extensive prime lists and conjectural density formulas support infinitude, but no theorem proves it for this quadratic polynomial. Results about large prime factors or almost primes do not suffice.",
    smallestStep: "Reproduce a bounded segment of the cited prime enumeration with primality certificates, then investigate a specific congruence obstruction or an explicit error estimate in its counting heuristic.",
    successCriterion: "A reproducible certified segment and a proved local obstruction or explicit conditional estimate, with numerical evidence clearly separated from infinitude.",
    agentFit: 59,
    scale: "frontier",
    location: { name: "Bowie, Maryland (Grantham and Graves's enumeration)", longitude: -76.7791, latitude: 38.9428 },
    tags: ["polynomial primes", "sieves", "primality certificates"],
    tools: ["PARI/GP", "SageMath", "Arb"],
    sources: [
      { title: "Primes of the Form m²+1 and Goldbach's 'Other Other' Conjecture", url: "https://arxiv.org/html/2502.03513v1", kind: "primary", passage: "More than a century later, the problem still resists all attempts." },
    ],
  }),
];
