import type { Field, OpenProblem } from "@/lib/types";

const prompt = (title: string, goal: string) => `You are beginning a serious research attempt on: ${title}.

Your first objective is not to claim a proof. It is to ${goal}

Work reproducibly:
1. Restate the problem with exact definitions and identify every quantifier.
2. Search for the strongest known results and failed approaches. Cite primary sources.
3. Reproduce at least one known result computationally or formally before extending it.
4. Propose three bounded subproblems, ranked by expected information gain.
5. Choose one subproblem and build a falsifiable experiment, proof sketch, or verification harness.
6. Keep a claim ledger: proven, experimentally supported, conjectural, and unknown.

Never present numerical evidence as proof. Return code, tests, intermediate artifacts, and a research log.`;

export const fieldColors: Record<Field, string> = {
  Mathematics: "#e7a863",
  Physics: "#8fb8cf",
  "Computer science": "#b8aca0",
  Biology: "#b77d73",
  Chemistry: "#a997bf",
};

export const problems: OpenProblem[] = [
  {
    id: "erdos-straus",
    title: "Erdős-Straus conjecture",
    field: "Mathematics",
    subfield: "Number theory",
    summary: "Can every fraction 4/n be written as the sum of three positive unit fractions?",
    statement: "For every integer n ≥ 2, do positive integers x, y and z exist such that 4/n = 1/x + 1/y + 1/z?",
    whyOpen: "The conjecture has survived enormous computational verification and many congruence-class arguments, but no finite family of identities is known to cover every integer.",
    smallestStep: "Search systematically for new parametric identities that eliminate a previously uncovered residue class, then formally verify the identity and its domain.",
    agentFit: 92,
    scale: "foothold",
    introduced: 1948,
    location: { name: "Budapest, Hungary", longitude: 19.0402, latitude: 47.4979 },
    tags: ["Diophantine", "symbolic search", "formal proof"],
    tools: ["Lean", "SageMath", "SAT/SMT"],
    sources: [
      { title: "The On-Line Encyclopedia of Integer Sequences: Erdős-Straus", url: "https://oeis.org/wiki/Erd%C5%91s-Straus_conjecture", kind: "index" },
      { title: "An Introduction to the Erdős-Straus Conjecture", url: "https://arxiv.org/abs/1204.1104", kind: "survey" },
    ],
    starterPrompt: prompt("the Erdős-Straus conjecture", "discover and verify a useful new parametric identity or residue-class reduction."),
    verified: "2026-09-04",
  },
  {
    id: "lonely-runner",
    title: "Lonely runner conjecture",
    field: "Mathematics",
    subfield: "Diophantine approximation",
    summary: "At some time, must every runner on a circular track be far from all the others?",
    statement: "For k runners with distinct constant speeds, is every runner at some time at distance at least 1/k from every other runner?",
    whyOpen: "The statement connects view-obstruction geometry, chromatic numbers and simultaneous Diophantine approximation. General proofs remain elusive despite progress for fixed dimensions.",
    smallestStep: "Generate extremal speed sets in the first unresolved dimension and use exact arithmetic to classify their obstruction patterns.",
    agentFit: 88,
    scale: "foothold",
    introduced: 1967,
    location: { name: "Jerusalem, Israel", longitude: 35.2137, latitude: 31.7683 },
    tags: ["geometry", "optimization", "exact computation"],
    tools: ["Python", "ILP", "Lean"],
    sources: [
      { title: "The Lonely Runner Conjecture turns 60", url: "https://arxiv.org/abs/1910.06077", kind: "survey" },
    ],
    starterPrompt: prompt("the lonely runner conjecture", "map extremal instances and extract a lemma that reduces one unresolved finite-dimensional case."),
    verified: "2026-09-04",
  },
  {
    id: "odd-perfect",
    title: "Odd perfect numbers",
    field: "Mathematics",
    subfield: "Number theory",
    summary: "Does any odd integer equal the sum of its proper divisors?",
    statement: "Does there exist an odd positive integer n such that σ(n) = 2n?",
    whyOpen: "Any example must obey severe structural restrictions and be astronomically large, yet no contradiction rules out every possible factorization pattern.",
    smallestStep: "Encode current structural constraints into a verified constraint solver and seek either contradictions or missing cases in published bounds.",
    agentFit: 84,
    scale: "frontier",
    introduced: 300,
    location: { name: "Alexandria, Egypt", longitude: 29.9187, latitude: 31.2001 },
    tags: ["divisors", "constraint solving", "ancient"],
    tools: ["SageMath", "Z3", "Lean"],
    sources: [
      { title: "Odd perfect numbers: old and new results", url: "https://arxiv.org/abs/1204.1450", kind: "survey" },
    ],
    starterPrompt: prompt("the existence of odd perfect numbers", "construct a machine-checkable map of known constraints and test one bounded factor-pattern family."),
    verified: "2026-09-04",
  },
  {
    id: "hadamard",
    title: "Hadamard matrix conjecture",
    field: "Mathematics",
    subfield: "Combinatorics",
    summary: "Does a perfectly orthogonal ±1 matrix exist in every order divisible by four?",
    statement: "For every positive integer n divisible by 4, does an n × n matrix H with entries ±1 exist such that HHᵀ = nI?",
    whyOpen: "Many infinite construction families and extensive tables exist, but the gap between them has not been closed for all multiples of four.",
    smallestStep: "Target a specific unknown order with symmetry reduction, SAT search and independently checkable certificates.",
    agentFit: 96,
    scale: "foothold",
    introduced: 1893,
    location: { name: "Paris, France", longitude: 2.3522, latitude: 48.8566 },
    tags: ["matrix", "SAT", "certificate"],
    tools: ["CaDiCaL", "Python", "proof certificates"],
    sources: [
      { title: "Hadamard matrices", url: "https://www.hadamard.ca/", kind: "index" },
    ],
    starterPrompt: prompt("the Hadamard matrix conjecture", "identify a high-value unresolved order and produce a reproducible symmetry-reduced search plan with verifiable certificates."),
    verified: "2026-09-04",
  },
  {
    id: "moving-sofa",
    title: "Moving sofa problem",
    field: "Mathematics",
    subfield: "Geometry",
    summary: "What is the largest rigid shape that can turn through a unit-width right-angled hallway?",
    statement: "Determine the supremal area of a planar shape that can be moved around a right-angled corner in a corridor of width one.",
    whyOpen: "Gerver’s construction gives the best classical lower bound, while recent computer-assisted work has tightened the upper bound without meeting it.",
    smallestStep: "Reproduce the current bounds, parameterize a richer family of smooth shapes, and optimize it with interval-certified collision checks.",
    agentFit: 94,
    scale: "foothold",
    introduced: 1966,
    location: { name: "Vienna, Austria", longitude: 16.3738, latitude: 48.2082 },
    tags: ["geometry", "numerical optimization", "interval arithmetic"],
    tools: ["Julia", "interval arithmetic", "CAD"],
    sources: [
      { title: "A new upper bound on the moving sofa problem", url: "https://arxiv.org/abs/2411.19826", kind: "primary" },
    ],
    starterPrompt: prompt("the moving sofa problem", "reproduce a known construction and test a strictly broader parameterized family with certified collision constraints."),
    verified: "2026-09-04",
  },
  {
    id: "collatz",
    title: "Collatz conjecture",
    field: "Mathematics",
    subfield: "Dynamical systems",
    summary: "Does repeatedly applying one simple parity rule eventually send every positive integer to 1?",
    statement: "Starting from n, replace even n by n/2 and odd n by 3n+1. Does every positive integer eventually reach 1?",
    whyOpen: "The orbit mixes multiplication and division according to parity in a way that resists global control. Vast computation cannot cover infinitely many starting values.",
    smallestStep: "Reproduce a modern density result or search for a new invariant on a restricted family. Do not confuse verification with proof.",
    agentFit: 67,
    scale: "frontier",
    introduced: 1937,
    location: { name: "Hamburg, Germany", longitude: 9.9937, latitude: 53.5511 },
    tags: ["iteration", "density", "computation"],
    tools: ["C++", "Lean", "symbolic dynamics"],
    sources: [
      { title: "Almost all Collatz orbits attain almost bounded values", url: "https://arxiv.org/abs/1909.03562", kind: "primary" },
    ],
    starterPrompt: prompt("the Collatz conjecture", "select a bounded structural subproblem, reproduce the strongest relevant result, and search for an invariant rather than merely extending verification."),
    verified: "2026-09-04",
  },
  {
    id: "riemann",
    title: "Riemann hypothesis",
    field: "Mathematics",
    subfield: "Analytic number theory",
    summary: "Do all non-trivial zeros of the zeta function lie on one vertical line?",
    statement: "Every non-trivial zero of ζ(s) has real part 1/2.",
    whyOpen: "It is equivalent to extremely precise control of prime-number irregularity and touches large parts of modern number theory.",
    smallestStep: "Pick one explicit equivalent criterion and improve a finite bound, numerical method, or formalized dependency with rigorous error control.",
    agentFit: 42,
    scale: "monument",
    introduced: 1859,
    location: { name: "Göttingen, Germany", longitude: 9.9352, latitude: 51.5328 },
    tags: ["zeta function", "primes", "Clay Prize"],
    tools: ["Arb", "Lean", "analytic estimates"],
    sources: [
      { title: "Clay Mathematics Institute: Riemann Hypothesis", url: "https://www.claymath.org/millennium/riemann-hypothesis/", kind: "primary" },
    ],
    starterPrompt: prompt("the Riemann hypothesis", "choose one bounded equivalent criterion and improve its verified computational or formal frontier without claiming to attack the full hypothesis directly."),
    verified: "2026-09-04",
  },
  {
    id: "p-vs-np",
    title: "P versus NP",
    field: "Computer science",
    subfield: "Complexity theory",
    summary: "If a solution is quick to check, is it always quick to find?",
    statement: "Is the class P of problems solvable in polynomial time equal to NP, the class whose solutions are verifiable in polynomial time?",
    whyOpen: "Most natural proof techniques are blocked by formal barriers such as relativization, natural proofs and algebrization.",
    smallestStep: "Map one restricted circuit class or proof system, explicitly test known barriers, and seek a lower bound in a model not already exhausted.",
    agentFit: 36,
    scale: "monument",
    introduced: 1971,
    location: { name: "Toronto, Canada", longitude: -79.3832, latitude: 43.6532 },
    tags: ["complexity", "lower bounds", "Clay Prize"],
    tools: ["Lean", "SAT", "literature graph"],
    sources: [
      { title: "Clay Mathematics Institute: P vs NP", url: "https://www.claymath.org/millennium/p-vs-np-problem/", kind: "primary" },
    ],
    starterPrompt: prompt("P versus NP", "identify a restricted lower-bound question that escapes at least one known proof barrier and state the barrier analysis explicitly."),
    verified: "2026-09-04",
  },
  {
    id: "navier-stokes",
    title: "Navier-Stokes regularity",
    field: "Physics",
    subfield: "Fluid mechanics",
    summary: "Can a smooth three-dimensional fluid develop a singularity in finite time?",
    statement: "For incompressible 3D Navier-Stokes flow with smooth initial data, do smooth solutions exist for all time, or can blow-up occur?",
    whyOpen: "Energy estimates control average behaviour but not the multiscale concentration needed to rule out singularities.",
    smallestStep: "Reproduce a regularity criterion or probe a carefully defined family of initial conditions with validated numerics and error bounds.",
    agentFit: 58,
    scale: "monument",
    introduced: 1934,
    location: { name: "St Petersburg, Russia", longitude: 30.3351, latitude: 59.9343 },
    tags: ["PDE", "fluid", "Clay Prize"],
    tools: ["Dedalus", "interval numerics", "Lean"],
    sources: [
      { title: "Clay Mathematics Institute: Navier-Stokes Equation", url: "https://www.claymath.org/millennium/navier-stokes-equation/", kind: "primary" },
    ],
    starterPrompt: prompt("3D Navier-Stokes existence and smoothness", "reproduce a precise regularity criterion and design a validated numerical test on a bounded family of initial data."),
    verified: "2026-09-04",
  },
  {
    id: "yang-mills",
    title: "Yang-Mills mass gap",
    field: "Physics",
    subfield: "Quantum field theory",
    summary: "Why do quantum gauge fields produce particles with positive mass despite massless classical waves?",
    statement: "Construct a rigorous quantum Yang-Mills theory on ℝ⁴ for a compact simple gauge group and prove that it has a positive mass gap.",
    whyOpen: "Physicists have overwhelming numerical and experimental evidence, but a mathematically rigorous non-perturbative construction in four dimensions is missing.",
    smallestStep: "Formalize or computationally reproduce a lower-dimensional analogue, making every limit and assumption explicit.",
    agentFit: 31,
    scale: "monument",
    introduced: 1954,
    location: { name: "Upton, New York", longitude: -72.8868, latitude: 40.8682 },
    tags: ["gauge theory", "QFT", "Clay Prize"],
    tools: ["lattice simulation", "Lean", "symbolic algebra"],
    sources: [
      { title: "Clay Mathematics Institute: Yang-Mills and Mass Gap", url: "https://www.claymath.org/millennium/yang-mills-the-maths-gap/", kind: "primary" },
    ],
    starterPrompt: prompt("the Yang-Mills existence and mass gap problem", "select a lower-dimensional or lattice subproblem and make one rigorous, reproducible bridge toward the continuum theory."),
    verified: "2026-09-04",
  },
  {
    id: "dark-matter",
    title: "Identity of dark matter",
    field: "Physics",
    subfield: "Cosmology",
    summary: "What makes up the invisible matter inferred from gravity across the universe?",
    statement: "Identify the microscopic nature, production mechanism and interactions of the non-baryonic matter responsible for cosmological and galactic gravitational evidence.",
    whyOpen: "Multiple observations demand additional gravitating matter, but direct detection and collider searches have not selected a particle model.",
    smallestStep: "Choose one public survey or direct-detection dataset and test a neglected model signature with a preregistered statistical pipeline.",
    agentFit: 81,
    scale: "frontier",
    introduced: 1933,
    location: { name: "Pasadena, California", longitude: -118.1445, latitude: 34.1478 },
    tags: ["cosmology", "statistics", "public data"],
    tools: ["Astropy", "JAX", "Bayesian inference"],
    sources: [
      { title: "Particle Data Group: Dark Matter review", url: "https://pdg.lbl.gov/2025/reviews/rpp2025-rev-dark-matter.pdf", kind: "survey" },
    ],
    starterPrompt: prompt("the identity of dark matter", "select one public dataset and one falsifiable model signature, then build a preregistered analysis with synthetic-data validation."),
    verified: "2026-09-04",
  },
  {
    id: "matter-antimatter",
    title: "Matter-antimatter asymmetry",
    field: "Physics",
    subfield: "Particle cosmology",
    summary: "Why did the early universe leave matter behind instead of annihilating everything?",
    statement: "Explain the observed baryon asymmetry with a quantitatively viable mechanism consistent with laboratory and cosmological constraints.",
    whyOpen: "Known Standard Model CP violation appears insufficient, while proposed mechanisms span inaccessible energy scales and tightly constrained new physics.",
    smallestStep: "Build a living constraint map for one baryogenesis mechanism and identify a parameter region newly testable by a current experiment.",
    agentFit: 78,
    scale: "frontier",
    introduced: 1967,
    location: { name: "Moscow, Russia", longitude: 37.6173, latitude: 55.7558 },
    tags: ["baryogenesis", "CP violation", "constraints"],
    tools: ["symbolic algebra", "global fitting", "literature graph"],
    sources: [
      { title: "The origin of the matter-antimatter asymmetry", url: "https://arxiv.org/abs/1206.2942", kind: "survey" },
    ],
    starterPrompt: prompt("the cosmic matter-antimatter asymmetry", "construct a sourced constraint map for one baryogenesis mechanism and identify one parameter region testable with existing data."),
    verified: "2026-09-04",
  },
  {
    id: "high-tc",
    title: "Mechanism of high-temperature superconductivity",
    field: "Physics",
    subfield: "Condensed matter",
    summary: "What microscopic mechanism pairs electrons in unconventional superconductors?",
    statement: "Derive and experimentally discriminate the mechanism responsible for superconductivity in cuprates and related materials at temperatures beyond conventional phonon pairing.",
    whyOpen: "Competing orders, strong correlations and material complexity generate many plausible models with overlapping experimental signatures.",
    smallestStep: "Mine open spectroscopy data for a discriminating signature between two explicit mechanisms, with leakage-resistant validation.",
    agentFit: 86,
    scale: "frontier",
    introduced: 1986,
    location: { name: "Rüschlikon, Switzerland", longitude: 8.5555, latitude: 47.3068 },
    tags: ["materials", "many-body", "data mining"],
    tools: ["PyTorch", "tensor networks", "spectroscopy"],
    sources: [
      { title: "The challenge of unconventional superconductivity", url: "https://www.nature.com/articles/s41586-023-06751-9", kind: "survey" },
    ],
    starterPrompt: prompt("the mechanism of high-temperature superconductivity", "choose two competing mechanisms and find one quantitative signature that can discriminate between them in public data."),
    verified: "2026-09-04",
  },
  {
    id: "abiogenesis",
    title: "Chemical origin of life",
    field: "Chemistry",
    subfield: "Prebiotic chemistry",
    summary: "How did non-living chemistry cross into self-sustaining Darwinian evolution?",
    statement: "Find a plausible, experimentally supported pathway from geochemical feedstocks to a compartmentalized, self-replicating and evolvable chemical system.",
    whyOpen: "Individual building blocks and reaction networks are known, but no end-to-end pathway works under one compatible set of early-Earth conditions.",
    smallestStep: "Build a reaction-condition compatibility graph from primary literature and identify one experimentally testable missing bridge.",
    agentFit: 91,
    scale: "foothold",
    introduced: 1924,
    location: { name: "Cambridge, United Kingdom", longitude: 0.1218, latitude: 52.2053 },
    tags: ["reaction network", "literature mining", "experiment design"],
    tools: ["RDKit", "knowledge graph", "lab automation"],
    sources: [
      { title: "The origins of life", url: "https://www.nature.com/collections/efjgcahcgh", kind: "index" },
    ],
    starterPrompt: prompt("the chemical origin of life", "construct a primary-source reaction compatibility graph and identify one missing bridge that can be tested under coherent conditions."),
    verified: "2026-09-04",
  },
  {
    id: "protein-dynamics",
    title: "Sequence-to-dynamics prediction",
    field: "Biology",
    subfield: "Structural biology",
    summary: "Can we predict a protein’s full functional motion, not only a likely static structure, from sequence?",
    statement: "Predict conformational ensembles, transition rates and environment-dependent functional dynamics from amino-acid sequence with experimentally calibrated uncertainty.",
    whyOpen: "Static structure prediction has advanced rapidly, but rare states, kinetics, ligands and cellular context determine much biological function.",
    smallestStep: "Benchmark one dynamics model against a leakage-audited set of NMR or single-molecule measurements and locate its sharpest failure mode.",
    agentFit: 93,
    scale: "foothold",
    introduced: 1970,
    location: { name: "Cambridge, Massachusetts", longitude: -71.0942, latitude: 42.3601 },
    tags: ["proteins", "benchmark", "molecular dynamics"],
    tools: ["OpenMM", "JAX", "NMR datasets"],
    sources: [
      { title: "Protein dynamics and function", url: "https://doi.org/10.1038/s41580-023-00680-9", kind: "survey" },
    ],
    starterPrompt: prompt("sequence-to-protein-dynamics prediction", "build a leakage-audited benchmark for one measurable dynamic property and expose the strongest current model failure."),
    verified: "2026-09-04",
  },
  {
    id: "bsd",
    title: "Birch and Swinnerton-Dyer conjecture",
    field: "Mathematics",
    subfield: "Arithmetic geometry",
    summary: "Can the rational solutions of an elliptic curve be read from its L-function?",
    statement: "For an elliptic curve E over the rationals, is the rank of E(Q) equal to the order of vanishing of L(E, s) at s = 1?",
    whyOpen: "Major cases are known, but the conjecture links analytic behavior and rational points through arithmetic invariants that remain uncontrolled in general.",
    smallestStep: "Choose a computationally accessible family, reproduce known ranks and analytic orders, then locate cases where existing descent or Heegner-point machinery leaves a precise gap.",
    agentFit: 63,
    scale: "monument",
    introduced: 1965,
    location: { name: "Cambridge, United Kingdom", longitude: 0.1218, latitude: 52.2053 },
    tags: ["elliptic curves", "L-functions", "Clay Prize"],
    tools: ["SageMath", "PARI/GP", "Lean"],
    sources: [{ title: "Clay Mathematics Institute: Birch and Swinnerton-Dyer", url: "https://www.claymath.org/millennium/birch-and-swinnerton-dyer-conjecture/", kind: "primary" }],
    starterPrompt: prompt("the Birch and Swinnerton-Dyer conjecture", "map one explicit elliptic-curve family where analytic and algebraic rank computations can be independently reproduced and a residual case isolated."),
    verified: "2026-09-04",
  },
  {
    id: "goldbach",
    title: "Goldbach conjecture",
    field: "Mathematics",
    subfield: "Additive number theory",
    summary: "Is every even integer greater than two the sum of two primes?",
    statement: "For every even integer n > 2, do primes p and q exist with n = p + q?",
    whyOpen: "The weak ternary form is proved and computation reaches enormous bounds, but current sieve methods cannot eliminate the parity obstruction for the binary statement.",
    smallestStep: "Reproduce a modern finite verification or density estimate with independently checked bounds, then test a sharply stated restricted family rather than extending a raw search.",
    agentFit: 72,
    scale: "frontier",
    introduced: 1742,
    location: { name: "St Petersburg, Russia", longitude: 30.3158, latitude: 59.9398 },
    tags: ["primes", "sieve methods", "verification"],
    tools: ["C++", "Arb", "Lean"],
    sources: [{ title: "Goldbach Conjecture", url: "https://mathworld.wolfram.com/GoldbachConjecture.html", kind: "index" }],
    starterPrompt: prompt("the strong Goldbach conjecture", "select one rigorous restricted statement, reproduce its best bound, and improve the verification or analytic certificate without confusing finite evidence with proof."),
    verified: "2026-09-04",
  },
  {
    id: "chromatic-plane",
    title: "Chromatic number of the plane",
    field: "Mathematics",
    subfield: "Geometric graph theory",
    summary: "How many colors are needed so that points exactly one unit apart never share a color?",
    statement: "Determine the chromatic number of the unit-distance graph on the Euclidean plane; it is currently known to lie between 5 and 7.",
    whyOpen: "Finite unit-distance graphs prove lower bounds while geometric colorings prove upper bounds, but neither side has closed the remaining gap.",
    smallestStep: "Search symmetry-reduced unit-distance graphs for a six-chromatic certificate or formalize a new class of measurable colorings with exhaustive verification.",
    agentFit: 96,
    scale: "foothold",
    introduced: 1950,
    location: { name: "Santa Monica, California", longitude: -118.4912, latitude: 34.0195 },
    tags: ["unit-distance graphs", "graph coloring", "SAT"],
    tools: ["CaDiCaL", "nauty", "proof certificates"],
    sources: [{ title: "The chromatic number of the plane is at least 5", url: "https://arxiv.org/abs/1804.02385", kind: "primary" }],
    starterPrompt: prompt("the chromatic number of the plane", "build a certificate-producing search over a new symmetry class of unit-distance graphs and independently verify every geometric constraint."),
    verified: "2026-09-04",
  },
  {
    id: "matrix-multiplication",
    title: "Matrix multiplication exponent",
    field: "Computer science",
    subfield: "Algorithms",
    summary: "Can two n by n matrices be multiplied in essentially quadratic time?",
    statement: "Is the exponent of square matrix multiplication ω equal to 2?",
    whyOpen: "Successive algebraic constructions lower the upper bound, but no known framework reaches two and meaningful lower bounds remain extremely weak.",
    smallestStep: "Implement one current tensor construction exactly, audit its asymptotics, and search a constrained family for a better degeneration with machine-checkable certificates.",
    agentFit: 91,
    scale: "frontier",
    introduced: 1969,
    location: { name: "Zürich, Switzerland", longitude: 8.5417, latitude: 47.3769 },
    tags: ["algorithms", "tensor rank", "algebraic complexity"],
    tools: ["SageMath", "Julia", "symbolic optimization"],
    sources: [{ title: "Which groups are amenable to proving exponent two for matrix multiplication?", url: "https://arxiv.org/abs/1712.02302", kind: "primary" }],
    starterPrompt: prompt("whether the matrix multiplication exponent equals two", "reproduce one modern tensor construction and run a certificate-producing search over a bounded extension of its parameter family."),
    verified: "2026-09-04",
  },
  {
    id: "unique-games",
    title: "Unique Games conjecture",
    field: "Computer science",
    subfield: "Approximation complexity",
    summary: "Is it computationally hard to distinguish almost-satisfiable unique constraint systems from highly unsatisfiable ones?",
    statement: "For every ε, δ > 0, is there an alphabet size for which distinguishing Unique Games instances of value at least 1 - ε from value at most δ is NP-hard?",
    whyOpen: "The conjecture explains optimal approximation thresholds for many problems, but powerful algorithms and partial hardness results have not settled the full parameter regime.",
    smallestStep: "Map one restricted constraint graph family, reproduce the best relaxation gap, and search for either a certified hard instance or an algorithm that breaks the predicted threshold.",
    agentFit: 87,
    scale: "frontier",
    introduced: 2002,
    location: { name: "Princeton, New Jersey", longitude: -74.6672, latitude: 40.3573 },
    tags: ["approximation", "semidefinite programming", "hardness"],
    tools: ["SDP solvers", "SAT", "Lean"],
    sources: [{ title: "The Unique Games Conjecture, integrality gap for cut problems and embeddability of negative type metrics", url: "https://arxiv.org/abs/1001.4596", kind: "survey" }],
    starterPrompt: prompt("the Unique Games conjecture", "choose one restricted instance family and reproduce its best algorithmic and integrality-gap thresholds before searching for a certified separation."),
    verified: "2026-09-04",
  },
  {
    id: "quantum-pcp",
    title: "Quantum PCP conjecture",
    field: "Computer science",
    subfield: "Quantum complexity",
    summary: "Does approximating the energy density of a local quantum system remain QMA-hard?",
    statement: "Is estimating the ground-state energy of a local Hamiltonian to constant relative accuracy QMA-hard?",
    whyOpen: "Entanglement creates both candidate hardness mechanisms and possible low-energy structure, while classical PCP reductions do not transfer cleanly.",
    smallestStep: "Reproduce a known games-formulation barrier on small instances and search for a finite counterexample or strengthening with exact tensor-network calculations.",
    agentFit: 84,
    scale: "frontier",
    introduced: 2006,
    location: { name: "Jerusalem, Israel", longitude: 35.2137, latitude: 31.7683 },
    tags: ["QMA", "Hamiltonians", "entanglement"],
    tools: ["tensor networks", "SDP", "exact diagonalization"],
    sources: [{ title: "The status of the quantum PCP conjecture", url: "https://arxiv.org/abs/2403.13084", kind: "survey" }],
    starterPrompt: prompt("the quantum PCP conjecture", "select one games-version subproblem, reproduce the known obstruction exactly, and test a bounded construction using certified numerical methods."),
    verified: "2026-09-04",
  },
  {
    id: "black-hole-information",
    title: "Black hole information problem",
    field: "Physics",
    subfield: "Quantum gravity",
    summary: "How does information escape, or survive, when a black hole evaporates?",
    statement: "Reconcile unitary quantum evolution with semiclassical Hawking evaporation and the apparently thermal radiation emitted by a black hole.",
    whyOpen: "Recent entropy calculations reproduce a unitary Page curve in controlled settings, but the microscopic mechanism and its extension to realistic evaporating black holes remain disputed.",
    smallestStep: "Reproduce an island-formula calculation in a tractable model and test exactly which assumptions fail under one controlled deformation.",
    agentFit: 69,
    scale: "frontier",
    introduced: 1976,
    location: { name: "Cambridge, United Kingdom", longitude: 0.1166, latitude: 52.2058 },
    tags: ["quantum gravity", "entropy", "unitarity"],
    tools: ["symbolic algebra", "tensor networks", "literature graph"],
    sources: [{ title: "The Black Hole Information Problem", url: "https://pubmed.ncbi.nlm.nih.gov/PMC12191829", kind: "survey" }],
    starterPrompt: prompt("the black hole information problem", "reproduce one island or Page-curve calculation and isolate a single assumption whose controlled failure gives a discriminating result."),
    verified: "2026-09-04",
  },
  {
    id: "hubble-tension",
    title: "Origin of the Hubble tension",
    field: "Physics",
    subfield: "Observational cosmology",
    summary: "Why do early- and late-universe measurements infer different cosmic expansion rates?",
    statement: "Determine whether the statistically persistent discrepancy in inferred H₀ arises from unmodeled systematics, new cosmological physics, or both.",
    whyOpen: "Independent distance ladders and early-universe fits remain difficult to reconcile, while proposed solutions often damage agreement with other observables.",
    smallestStep: "Reanalyse one public calibration rung or one proposed extension under a preregistered systematics model and publish the full covariance audit.",
    agentFit: 92,
    scale: "foothold",
    introduced: 2019,
    location: { name: "Baltimore, Maryland", longitude: -76.6158, latitude: 39.3299 },
    tags: ["cosmology", "distance ladder", "systematics"],
    tools: ["Astropy", "Bayesian inference", "public survey data"],
    sources: [{ title: "In the realm of the Hubble tension", url: "https://arxiv.org/abs/2103.01183", kind: "survey" }],
    starterPrompt: prompt("the origin of the Hubble tension", "select one public dataset and reproduce a complete calibration or covariance analysis that discriminates systematics from one explicit new-physics model."),
    verified: "2026-09-04",
  },
  {
    id: "glass-transition",
    title: "Microscopic theory of the glass transition",
    field: "Chemistry",
    subfield: "Physical chemistry",
    summary: "Why do some liquids become rigid without crystallizing?",
    statement: "Derive a predictive microscopic account of the dramatic slowing, dynamic heterogeneity and possible thermodynamic transition in supercooled liquids.",
    whyOpen: "Competing kinetic and thermodynamic theories reproduce overlapping observations, and accessible timescales are far shorter than experimental relaxation near the glass transition.",
    smallestStep: "Benchmark two competing theories on the same open molecular-dynamics trajectories and identify one observable where their predictions provably diverge.",
    agentFit: 89,
    scale: "foothold",
    introduced: 1948,
    location: { name: "Paris, France", longitude: 2.3376, latitude: 48.8607 },
    tags: ["supercooled liquids", "statistical mechanics", "simulation"],
    tools: ["LAMMPS", "JAX", "Bayesian model comparison"],
    sources: [{ title: "Theoretical perspective on the glass transition and amorphous materials", url: "https://arxiv.org/abs/1007.4762", kind: "survey" }],
    starterPrompt: prompt("the microscopic origin of the glass transition", "choose two explicit theories and design a leakage-resistant simulation benchmark around one observable on which they make different predictions."),
    verified: "2026-09-04",
  },
  {
    id: "homochirality",
    title: "Origin of biological homochirality",
    field: "Chemistry",
    subfield: "Prebiotic chemistry",
    summary: "Why did life select one molecular handedness from initially symmetric chemistry?",
    statement: "Identify a plausible prebiotic mechanism that breaks chiral symmetry, amplifies the imbalance and propagates it through a chemically compatible network to biological homochirality.",
    whyOpen: "Many mechanisms create or amplify asymmetry in isolation, but none yet establishes an end-to-end path under one coherent set of early-Earth conditions.",
    smallestStep: "Build a compatibility graph of demonstrated symmetry-breaking and amplification reactions, then identify one missing interface suitable for a decisive experiment.",
    agentFit: 94,
    scale: "foothold",
    introduced: 1848,
    location: { name: "Strasbourg, France", longitude: 7.7521, latitude: 48.5734 },
    tags: ["chirality", "reaction networks", "origin of life"],
    tools: ["RDKit", "kinetic modeling", "lab automation"],
    sources: [{ title: "How does chiral information propagate in a prebiotic network?", url: "https://pubmed.ncbi.nlm.nih.gov/PMC7615580", kind: "survey" }],
    starterPrompt: prompt("the origin of biological homochirality", "map experimentally demonstrated chiral amplification routes into one condition-compatible network and locate a single missing reaction interface to test."),
    verified: "2026-09-04",
  },
  {
    id: "genotype-phenotype",
    title: "General genotype-to-phenotype prediction",
    field: "Biology",
    subfield: "Quantitative genetics",
    summary: "Can an organism's traits be predicted from its genome across populations and environments?",
    statement: "Predict complex quantitative phenotypes from genotype with calibrated uncertainty that transfers across ancestry, environment and measurement context.",
    whyOpen: "Polygenicity, epistasis, gene-environment interactions, population structure and phenotype definition create severe transfer and identifiability failures.",
    smallestStep: "Choose one open cohort and phenotype, establish a leakage-audited cross-population baseline, and isolate the largest reproducible source of transfer failure.",
    agentFit: 95,
    scale: "foothold",
    introduced: 1909,
    location: { name: "Cambridge, Massachusetts", longitude: -71.1056, latitude: 42.3751 },
    tags: ["genetics", "causal inference", "generalization"],
    tools: ["Hail", "PyTorch", "polygenic scores"],
    sources: [{ title: "Open Problems in Human Trait Genetics", url: "https://arxiv.org/abs/2108.06684", kind: "survey" }],
    starterPrompt: prompt("general genotype-to-phenotype prediction", "build a leakage-audited cross-population benchmark for one quantitative trait and identify the strongest reproducible generalization failure."),
    verified: "2026-09-04",
  },
  {
    id: "enhancer-grammar",
    title: "Predictive enhancer grammar",
    field: "Biology",
    subfield: "Gene regulation",
    summary: "Can regulatory DNA sequence predict when, where and how strongly a gene is expressed?",
    statement: "Learn a causal, transferable mapping from enhancer sequence and cellular context to quantitative gene expression, including motif syntax and long-range interactions.",
    whyOpen: "High-throughput assays measure fragments outside native context, while combinatorial syntax, chromatin state and three-dimensional contacts confound sequence-only models.",
    smallestStep: "Build a held-out perturbation benchmark that separates motif recognition from causal syntax and test whether one model transfers across cell types.",
    agentFit: 96,
    scale: "foothold",
    introduced: 1981,
    location: { name: "Berkeley, California", longitude: -122.2585, latitude: 37.8719 },
    tags: ["enhancers", "gene expression", "causal sequence models"],
    tools: ["PyTorch", "MPRA data", "genome browsers"],
    sources: [{ title: "Decoding enhancer complexity with machine learning and high-throughput discovery", url: "https://pubmed.ncbi.nlm.nih.gov/PMC10176946", kind: "survey" }],
    starterPrompt: prompt("predictive enhancer grammar", "construct a cell-type transfer benchmark that distinguishes motif detection from causal regulatory syntax using held-out perturbations."),
    verified: "2026-09-04",
  },
  {
    id: "low-cloud-feedback",
    title: "Low-cloud feedback on climate sensitivity",
    field: "Physics",
    subfield: "Climate physics",
    summary: "How strongly will tropical low clouds amplify or damp future climate change?",
    statement: "Determine the sign, magnitude and physical controls of tropical marine low-cloud feedback under sustained warming well enough to materially narrow equilibrium climate-sensitivity estimates.",
    whyOpen: "Global models and cloud-resolving simulations still disagree about how parameterized versus resolved convection changes cloud amount near the trade inversion, while the observational record is too short and entangled with meteorological variability to isolate the forced response cleanly.",
    smallestStep: "Apply the same process-oriented diagnostic to public satellite observations and a matched ensemble of high-resolution simulations, then test which cloud-controlling factors remain stable across temporal and spatial scales.",
    agentFit: 93,
    scale: "foothold",
    introduced: 1979,
    location: { name: "Hamburg, Germany", longitude: 9.9937, latitude: 53.5511 },
    tags: ["climate change", "cloud feedback", "climate sensitivity", "public observations"],
    tools: ["xarray", "Earth observation", "causal inference"],
    sources: [
      { title: "Mechanisms and model diversity of trade-wind shallow cumulus cloud feedbacks", url: "https://pubmed.ncbi.nlm.nih.gov/PMC5717165", kind: "survey" },
      { title: "Perturbing parameters to understand cloud contributions to climate change", url: "https://arxiv.org/abs/2310.08665", kind: "primary" },
    ],
    starterPrompt: prompt("low-cloud feedback on climate sensitivity", "reproduce one process-oriented cloud-feedback diagnostic across matched public observations and high-resolution simulations, then identify a discriminating result that could rule out one mechanism."),
    verified: "2026-09-04",
  },
  {
    id: "antarctic-retreat-thresholds",
    title: "Thresholds for irreversible Antarctic ice loss",
    field: "Physics",
    subfield: "Cryosphere dynamics",
    summary: "Which warming and ocean-forcing thresholds make Antarctic ice-sheet retreat self-sustaining under climate change?",
    statement: "Constrain the onset thresholds, retreat rates and reversibility of marine ice-sheet and ice-cliff instabilities sufficiently to distinguish recoverable mass loss from committed multi-century sea-level rise.",
    whyOpen: "The direct record is far shorter than the response timescale, subglacial topography and ocean forcing remain incompletely observed, and competing ice-dynamic parameterizations produce substantially different threshold behavior.",
    smallestStep: "Choose one well-observed Antarctic basin and benchmark competing instability parameterizations against the same paleo, satellite and ocean-forcing constraints with a complete uncertainty budget.",
    agentFit: 90,
    scale: "frontier",
    introduced: 1978,
    location: { name: "Cambridge, United Kingdom", longitude: 0.1218, latitude: 52.2053 },
    tags: ["climate change", "ice sheets", "sea-level rise", "tipping points"],
    tools: ["PISM", "xarray", "Bayesian calibration"],
    sources: [
      { title: "Decadal-scale onset and termination of Antarctic ice-mass loss", url: "https://pubmed.ncbi.nlm.nih.gov/PMC8602255", kind: "primary" },
      { title: "Spatio-temporal variability across Antarctic ice-bed-ocean interfaces", url: "https://pubmed.ncbi.nlm.nih.gov/PMC6006349", kind: "survey" },
    ],
    starterPrompt: prompt("thresholds for irreversible Antarctic ice loss", "select one data-rich Antarctic basin, reproduce a published retreat experiment, and test one competing instability parameterization under an identical uncertainty model."),
    verified: "2026-09-04",
  },
  {
    id: "permafrost-carbon-feedback",
    title: "Permafrost carbon feedback under abrupt thaw",
    field: "Physics",
    subfield: "Earth system science",
    summary: "How much additional climate change will be driven by carbon released through gradual and abrupt permafrost thaw?",
    statement: "Estimate the timing, magnitude and gas composition of the permafrost carbon-climate feedback across gradual active-layer deepening and abrupt-thaw processes, with uncertainty calibrated against field observations.",
    whyOpen: "Circumpolar carbon stocks are heterogeneous, abrupt thaw is sparsely observed, microbial conversion controls the balance of carbon dioxide and methane, and many Earth-system models omit or simplify these coupled processes.",
    smallestStep: "Build a harmonized benchmark from open flux, active-layer and soil-carbon datasets, then quantify which omitted process contributes most to out-of-sample feedback uncertainty.",
    agentFit: 95,
    scale: "foothold",
    introduced: 1991,
    location: { name: "Fairbanks, Alaska", longitude: -147.7164, latitude: 64.8378 },
    tags: ["climate change", "permafrost", "carbon cycle", "methane"],
    tools: ["xarray", "geospatial ML", "uncertainty quantification"],
    sources: [
      { title: "A simplified, data-constrained estimate of the permafrost carbon-climate feedback", url: "https://pubmed.ncbi.nlm.nih.gov/PMC4608038", kind: "primary" },
      { title: "Timescales of the permafrost carbon cycle and temperature overshoot", url: "https://pubmed.ncbi.nlm.nih.gov/PMC8113593", kind: "primary" },
    ],
    starterPrompt: prompt("the permafrost carbon feedback under abrupt thaw", "assemble a leakage-resistant public-data benchmark and isolate the omitted process that contributes most to out-of-sample carbon-flux uncertainty."),
    verified: "2026-09-04",
  },
  {
    id: "ambient-nitrogen-fixation",
    title: "Ambient catalytic nitrogen fixation",
    field: "Chemistry",
    subfield: "Catalysis",
    summary: "Can nitrogen be converted to ammonia efficiently under mild conditions using renewable energy?",
    statement: "Develop a selective, durable catalytic route from N₂ to ammonia at near-ambient temperature and pressure whose full-system energy and carbon cost beats conventional production.",
    whyOpen: "The nitrogen triple bond is exceptionally inert, competing hydrogen evolution dominates many systems, and trace contamination has produced false positive ammonia claims.",
    smallestStep: "Reproduce one catalyst under isotope-labeled controls and a complete contamination protocol, then publish a calibrated detection and energy-efficiency ledger.",
    agentFit: 88,
    scale: "foothold",
    introduced: 2003,
    location: { name: "Tokyo, Japan", longitude: 139.6503, latitude: 35.6762 },
    tags: ["ammonia", "electrocatalysis", "isotope controls"],
    tools: ["DFT", "Bayesian optimization", "lab automation"],
    sources: [{ title: "Ammonia from dinitrogen at ambient conditions by organometallic catalysts", url: "https://pubmed.ncbi.nlm.nih.gov/PMC9682445", kind: "survey" }],
    starterPrompt: prompt("ambient catalytic nitrogen fixation", "select one reported catalyst and design an isotope-controlled reproduction that accounts for contamination, selectivity and full-system energy use."),
    verified: "2026-09-04",
  },
];

export const problemById = new Map(problems.map((problem) => [problem.id, problem]));

export const fields = Object.keys(fieldColors) as Field[];
