import type { OpenProblem } from "@/lib/types";

const scienceProblem = (
  problem: Omit<OpenProblem, "starterPrompt" | "verified">,
): OpenProblem => ({
  ...problem,
  verified: "2026-09-06",
  starterPrompt: `Investigate: ${problem.title}.

Question: ${problem.statement}
Begin with this bounded task: ${problem.smallestStep}
Available resources and limits: ${problem.executionResources}
Completion criterion: ${problem.successCriterion}

Read the cited papers and check for later results before beginning. Reproduce the relevant baseline, preserve data provenance, and reserve an independent test set. Separate measured facts, model assumptions, and new hypotheses. Report uncertainty and failed checks. A successful first step is not a solution to the whole problem. Return reproducible code, results, and a short research log.`,
});

export const additionalScienceProblems: OpenProblem[] = [
  scienceProblem({
    id: "neutrino-mass-ordering",
    title: "Which neutrino is heaviest?",
    field: "Physics",
    subfield: "Neutrino physics",
    summary: "Are the two closely spaced neutrino masses lighter or heavier than the third?",
    statement: "Determine whether the third neutrino mass state lies above or below the first two, with a result robust to detector calibration, neutrino interaction models, and oscillation-parameter uncertainty.",
    whyOpen: "Oscillations measure mass differences, but their interpretation involves overlapping parameters and experimental uncertainties. The joint T2K-NOvA analysis found no strong preference between orderings; later proposals still target a decisive measurement.",
    smallestStep: "Reproduce a published oscillation likelihood using released probability grids, then measure how the ordering preference changes under each documented uncertainty model.",
    agentFit: 80,
    scale: "frontier",
    location: { name: "Kamioka, Japan (neutrino observatory)", longitude: 137.31, latitude: 36.43 },
    tags: ["neutrinos", "mass ordering", "likelihoods", "public data"],
    tools: ["GLoBES", "Python", "Bayesian inference"],
    sources: [
      { title: "Joint neutrino oscillation analysis from the T2K and NOvA experiments", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12545204/", kind: "primary", publishedAt: "2025-10-22", passage: "The data show no strong preference for either mass ordering" },
      { title: "Neutrino mass ordering from the next Galactic supernova at DUNE, HK, and JUNO", url: "https://arxiv.org/abs/2606.06580", kind: "primary", publishedAt: "2026-06-04", sourceType: "preprint" },
    ],
    agentReadiness: "hybrid",
    executionResources: "Released likelihood grids support a desktop analysis; event-level recalibration needs collaboration access, and a decisive result may require more detector exposure.",
    successCriterion: "Recover the published ordering comparison within its stated accuracy and identify which uncertainty most changes it, without treating a simulation forecast as a detection.",
  }),
  scienceProblem({
    id: "majorana-neutrino",
    title: "Is the neutrino its own antiparticle?",
    field: "Physics",
    subfield: "Particle physics",
    summary: "Neutrinos may have a kind of mass that makes matter and antimatter versions identical.",
    statement: "Establish whether neutrinos are Majorana particles, including whether neutrinoless double beta decay occurs and which physical mechanism would account for an observed rate.",
    whyOpen: "Searches continue to set limits rather than detect the decay. Turning a decay limit into a neutrino-mass limit depends on nuclear calculations and on the assumed decay mechanism; a null result does not establish that neutrinos are Dirac particles.",
    smallestStep: "Reproduce the LEGEND-200 published half-life constraint and propagate several published nuclear matrix-element calculations into an explicitly assumption-dependent mass bound.",
    agentFit: 75,
    scale: "frontier",
    introduced: 1937,
    location: { name: "Gran Sasso, Italy (LEGEND experiment)", longitude: 13.57, latitude: 42.45 },
    tags: ["neutrinos", "antimatter", "rare decays", "nuclear uncertainty"],
    tools: ["Python", "likelihood analysis", "nuclear data tables"],
    sources: [
      { title: "First Results on the Search for Lepton Number Violating Neutrinoless Double Beta Decay with the LEGEND-200 Experiment", url: "https://arxiv.org/abs/2505.10440", kind: "primary", publishedAt: "2025-05-15", passage: "reveals no evidence for a signal" },
    ],
    agentReadiness: "hybrid",
    executionResources: "Published spectra and nuclear calculations permit a reproducible analysis. Discovery requires a sufficiently sensitive underground experiment and independent background checks.",
    successCriterion: "Match the published limit and report the spread from nuclear and statistical assumptions separately, including the limits of reconstructing a likelihood from published figures.",
  }),
  scienceProblem({
    id: "dark-energy-evolution",
    title: "Does dark energy change with time?",
    field: "Physics",
    subfield: "Cosmology",
    summary: "Is cosmic acceleration driven by a constant energy density or something that evolves?",
    statement: "Determine whether the dark-energy equation of state differs from the cosmological-constant value w = -1 over cosmic history, after accounting for calibration, dataset choice, and model flexibility.",
    whyOpen: "DESI DR2 combined with other measurements favors some evolving models, but the strength depends on the supernova sample and cosmological assumptions. A better fit in one parameterization does not identify a new physical component.",
    smallestStep: "Reproduce the public DESI DR2 distance-likelihood fit, then repeat the same model comparison across supernova samples while keeping priors and nuisance treatment fixed.",
    agentFit: 91,
    scale: "frontier",
    introduced: 1998,
    location: { name: "Kitt Peak, Arizona (DESI telescope)", longitude: -111.60, latitude: 31.96 },
    tags: ["dark energy", "cosmic expansion", "model comparison", "DESI"],
    tools: ["Cobaya", "CLASS", "public likelihoods"],
    sources: [
      { title: "DESI DR2 Results II: Measurements of Baryon Acoustic Oscillations and Cosmological Constraints", url: "https://arxiv.org/abs/2503.14738", kind: "primary", publishedAt: "2025-03-18", passage: "depending on which SNe sample is used" },
    ],
    agentReadiness: "hybrid",
    executionResources: "Public cosmological likelihoods and a workstation or small compute cluster. Independent survey calibration and additional observations remain outside a software-only result.",
    successCriterion: "Reproduce the baseline constraints and report how the evidence changes with dataset and prior choices, including a posterior-predictive check on held-out distances.",
  }),
  scienceProblem({
    id: "neutron-lifetime-discrepancy",
    title: "Why do neutron lifetime measurements disagree?",
    field: "Physics",
    subfield: "Precision measurement",
    summary: "Different ways of counting neutron decays still give incompatible lifetimes.",
    statement: "Explain the disagreement between proton-counting beam measurements and trapped-neutron lifetime measurements with a quantitatively tested uncertainty model or independently verified new physics.",
    whyOpen: "The January 2026 experimental review still reports a substantial discrepancy. A newer electron-counting beam result agrees with bottle measurements, so a simple division between every beam and every bottle experiment is already inadequate.",
    smallestStep: "Build a measurement-level dataset with separate detector, flux, storage-loss, and shared-calibration uncertainties; compare experiment-family and method-independent hierarchical fits.",
    agentFit: 86,
    scale: "foothold",
    location: { name: "Villigen, Switzerland (PSI lifetime workshop)", longitude: 8.23, latitude: 47.54 },
    tags: ["neutron", "measurement discrepancy", "systematic errors"],
    tools: ["Python", "Stan", "uncertainty propagation"],
    sources: [
      { title: "A new results of neutron lifetime measurement with cold neutron beam at J-PARC", url: "https://indico.psi.ch/event/17167/contributions/57991/", kind: "primary", publishedAt: "2025-09-13", sourceType: "experimental workshop presentation" },
      { title: "The beam-bottle debate at PSI", url: "https://cerncourier.com/a/the-beam-bottle-debate-at-psi/", kind: "survey", publishedAt: "2026-01-14", passage: "a longstanding tension between two measurement techniques continues" },
    ],
    agentReadiness: "hybrid",
    executionResources: "Published measurement budgets support a statistical audit. Testing a proposed detector bias requires apparatus data or a new controlled measurement.",
    successCriterion: "Reproduce the reported measurement-family averages and show which plausible shared uncertainties can or cannot explain the discrepancy without silently inflating all errors.",
  }),
  scienceProblem({
    id: "ultrahigh-energy-cosmic-rays",
    title: "Where do the highest-energy cosmic rays come from?",
    field: "Physics",
    subfield: "Astroparticle physics",
    summary: "Which objects accelerate atomic nuclei to energies far beyond human accelerators?",
    statement: "Identify a source population that jointly explains the energy spectrum, nuclear composition, and sky pattern of ultra-high-energy cosmic rays after propagation through radiation and magnetic fields.",
    whyOpen: "Large-scale arrival-direction anisotropy is established, but it does not identify individual accelerators. Unknown magnetic deflections, mixed nuclear composition, and air-shower modeling can make different source populations look similar.",
    smallestStep: "Use the public Pierre Auger event sample to reproduce a published angular statistic, then test one catalog association against exposure-matched randomized skies and magnetic-deflection sensitivity cases.",
    agentFit: 88,
    scale: "frontier",
    location: { name: "Malargüe, Argentina (Pierre Auger Observatory)", longitude: -69.59, latitude: -35.47 },
    tags: ["cosmic rays", "astronomy", "source identification", "public data"],
    tools: ["CRPropa", "HEALPix", "Astropy"],
    sources: [
      { title: "A composition-informed search for large-scale anisotropy with the Pierre Auger Observatory", url: "https://arxiv.org/abs/2507.08564", kind: "primary", publishedAt: "2025-07-11", sourceType: "collaboration conference paper" },
      { title: "The Pierre Auger Observatory: Results and Prospects", url: "https://arxiv.org/abs/2504.10333", kind: "survey", publishedAt: "2025-04-14" },
    ],
    agentReadiness: "hybrid",
    executionResources: "The open event subset supports limited analyses; it does not provide every composition estimator or the statistical power of the full collaboration dataset.",
    successCriterion: "Recover the expected exposure distribution and a documented baseline statistic, then quantify trials and magnetic-field uncertainty for a preregistered association test.",
  }),
  scienceProblem({
    id: "fast-radio-burst-populations",
    title: "Do all fast radio bursts repeat?",
    field: "Physics",
    subfield: "Radio astronomy",
    summary: "Are apparently one-off radio flashes a different population, or repeaters we have barely observed?",
    statement: "Determine whether one physical population with a distribution of burst rates explains repeating and apparently one-off fast radio bursts, or whether a genuinely non-repeating component is required.",
    whyOpen: "The 2026 CHIME analysis finds that models with 50-100% of sources repeating fit the observations comparably well. Limited observing time, changing sensitivity, and overlapping burst shapes leave the underlying populations unresolved.",
    smallestStep: "Reproduce the CHIME repeating-source rate model with its observing-window and detection-threshold assumptions, then use simulated catalogs to test whether a non-repeating fraction is identifiable.",
    agentFit: 94,
    scale: "foothold",
    location: { name: "Penticton, Canada (CHIME telescope)", longitude: -119.62, latitude: 49.32 },
    tags: ["fast radio bursts", "selection effects", "population inference"],
    tools: ["Astropy", "survival analysis", "simulation-based calibration"],
    sources: [
      { title: "Discovery of 30 Repeating Fast Radio Burst Sources and Uniform Population Statistics of 80 Repeating Sources from CHIME/FRB", url: "https://arxiv.org/abs/2605.08410", kind: "primary", publishedAt: "2026-05-08", sourceType: "preprint" },
      { title: "Semi-supervised morphological classification of fast radio bursts from the second CHIME/FRB catalogue", url: "https://arxiv.org/abs/2607.13148", kind: "primary", publishedAt: "2026-07-14", sourceType: "preprint" },
    ],
    agentReadiness: "hybrid",
    executionResources: "Public catalogs and released selection information support population modeling. Missing exposure information must be treated explicitly; longer telescope follow-up is needed to turn some one-offs into confirmed repeaters.",
    successCriterion: "Recover the paper's broad allowed repeating fraction and report simulation-calibrated limits on what the available sample can distinguish.",
  }),
  scienceProblem({
    id: "connectome-function-transfer",
    title: "How much brain activity can wiring predict?",
    field: "Biology",
    subfield: "Computational neuroscience",
    summary: "A wiring diagram constrains a brain, but does it predict responses to unfamiliar inputs?",
    statement: "Determine which neural responses and perturbation effects can be predicted from measured connectivity and limited physiology across tasks, rather than only within the task used to fit a model.",
    whyOpen: "Connectome-constrained models already predict responses in the fly visual system. Wiring does not uniquely fix cellular dynamics, and later studies still debate which predictions require exact connectivity rather than coarse network statistics.",
    smallestStep: "Reproduce the published fly visual-system model and compare its predictions on held-out stimuli with degree-preserving rewired models, keeping parameter count and training data matched.",
    agentFit: 92,
    scale: "foothold",
    location: { name: "Ashburn, Virginia (Janelia Research Campus)", longitude: -77.48, latitude: 39.07 },
    tags: ["connectome", "neural dynamics", "identifiability", "model comparison"],
    tools: ["PyTorch", "flyvis", "network analysis"],
    sources: [
      { title: "Connectome-constrained networks predict neural activity across the fly visual system", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11525180/", kind: "primary", publishedAt: "2024-09-11" },
      { title: "Separating wiring-specific from statistical control of dynamics in a complete connectome", url: "https://arxiv.org/abs/2606.17745", kind: "primary", publishedAt: "2026-06-16", sourceType: "preprint" },
    ],
    agentReadiness: "hybrid",
    executionResources: "The paper's public flyvis repository includes data, trained models, and notebooks. A GPU supports the benchmark. New causal tests require physiology or behavioral experiments.",
    successCriterion: "Measure the held-out prediction gain from exact wiring over matched null models, with uncertainty across training seeds and no reuse of test responses during fitting.",
  }),
  scienceProblem({
    id: "single-cell-fate-prediction",
    title: "Can a cell snapshot reveal its future?",
    field: "Biology",
    subfield: "Single-cell biology",
    summary: "Can gene-expression measurements reliably predict which type of cell a progenitor will become?",
    statement: "Predict a progenitor cell's later fate distribution from an earlier molecular measurement, with calibrated uncertainty that holds across independent lineage-tracing datasets and sampling conditions.",
    whyOpen: "Measuring RNA usually destroys the cell, so apparent trajectories often rely on assumptions rather than direct tracking. New RNA-velocity and transport methods improve selected benchmarks, but agreement with a known cell-type ordering is weaker evidence than out-of-sample lineage prediction.",
    smallestStep: "Compare cell2fate and MultistageOT on a public lineage-tracing dataset, separating whole clones and collection batches between training and evaluation.",
    agentFit: 94,
    scale: "foothold",
    location: { name: "Hinxton, United Kingdom (Wellcome Sanger Institute)", longitude: 0.19, latitude: 52.08 },
    tags: ["cell fate", "RNA velocity", "lineage tracing", "calibration"],
    tools: ["Scanpy", "cell2fate", "optimal transport"],
    sources: [
      { title: "Cell2fate infers RNA velocity modules to improve cell fate prediction", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11978503/", kind: "primary", publishedAt: "2025-03-03" },
      { title: "MultistageOT: Multistage optimal transport infers trajectories from a snapshot of single-cell data", url: "https://arxiv.org/abs/2502.05241", kind: "primary", publishedAt: "2025-02-07", sourceType: "preprint" },
    ],
    agentReadiness: "agent-ready",
    executionResources: "Public expression matrices and clone labels permit the benchmark on a workstation. The target is prediction from existing data; validating a new biological intervention would need an experiment.",
    successCriterion: "Report clone-held-out fate prediction and probability calibration, and show whether gains survive batch shifts and reduced RNA counts.",
  }),
  scienceProblem({
    id: "microbial-community-transfer",
    title: "Can microbial community models transfer between environments?",
    field: "Biology",
    subfield: "Microbial ecology",
    summary: "Predicting which microbes persist remains difficult when their surroundings change.",
    statement: "Predict community composition in a previously unseen natural environment using measured environmental conditions and ecological interactions, with uncertainty that separates missing drivers from measurement noise.",
    whyOpen: "Environmental filtering and interactions change with location and spatial scale. Recent work finds that predators can make communities more alike locally but more different globally, so a model fitted at one scale may learn the wrong transferable relationship.",
    smallestStep: "Reanalyze released environmental community data using region-held-out validation, comparing environment-only, spatial, and predator-aware models without selecting or modifying organisms.",
    agentFit: 91,
    scale: "foothold",
    location: { name: "Moscow, Russia (Gause's competition experiments)", longitude: 37.62, latitude: 55.75 },
    tags: ["ecology", "community assembly", "spatial transfer", "public observations"],
    tools: ["R", "community ecology models", "spatial cross-validation"],
    sources: [
      { title: "Predator-mediated local convergence fosters global microbial community divergence", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC13000328/", kind: "primary", publishedAt: "2026-03-18", passage: "promoting local convergence" },
    ],
    agentReadiness: "agent-ready",
    executionResources: "Published observational community tables and environmental metadata. Limit the first study to natural-community analysis; collection of new field observations remains a separate activity.",
    successCriterion: "Show whether adding predator information improves held-out regional predictions beyond spatial and environmental baselines, with sampling-depth and compositional-data checks.",
  }),
  scienceProblem({
    id: "plankton-coexistence-mechanisms",
    title: "What keeps so many plankton species coexisting?",
    field: "Biology",
    subfield: "Theoretical ecology",
    summary: "Many plankton species share a small set of resources, yet no single explanation predicts their diversity.",
    statement: "Determine which combination of resource differences, density dependence, predation, and environmental variation quantitatively explains persistent plankton coexistence across measured ecosystems.",
    whyOpen: "Many models permit coexistence, so the paradox is not a lack of possible mechanisms. The unresolved task is distinguishing their contributions and predicting abundance and diversity beyond the system used to fit them.",
    smallestStep: "Reproduce the recent density-dependent consumer-resource model, then compare it with a resource-only model on a public plankton time series using blocked future-time validation.",
    agentFit: 91,
    scale: "foothold",
    introduced: 1961,
    location: { name: "New Haven, Connecticut (Hutchinson's research at Yale)", longitude: -72.93, latitude: 41.31 },
    tags: ["biodiversity", "plankton", "coexistence", "dynamical systems"],
    tools: ["Julia", "ODE solvers", "ecological time series"],
    sources: [
      { title: "Density Dependence Promotes Species Coexistence and Provides a Unifying Explanation for Distinct Productivity-Diversity Relationships", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12719913/", kind: "primary", publishedAt: "2025-12-21" },
      { title: "Interspecific information use facilitates species coexistence in ecosystems", url: "https://arxiv.org/abs/2511.10520", kind: "primary", publishedAt: "2025-11-13", sourceType: "preprint" },
    ],
    agentReadiness: "agent-ready",
    executionResources: "Published model equations and open ecological time series. Field data may not identify every interaction; report indistinguishable mechanisms rather than asserting a unique cause.",
    successCriterion: "Reproduce the published coexistence behavior and identify a measurable time-series prediction on which the competing mechanisms differ under realistic sampling noise.",
  }),
  scienceProblem({
    id: "crystal-polymorph-selection",
    title: "Which crystal form will actually grow?",
    field: "Chemistry",
    subfield: "Crystallization",
    summary: "The most stable crystal structure is not always the one that first appears.",
    statement: "Predict which molecular-crystal polymorph nucleates under specified solution conditions, accounting for competing formation rates as well as thermodynamic stability.",
    whyOpen: "Crystal-structure searches rank possible structures, but kinetics, solvent interactions, and surface properties affect which structures are accessible. A 2026 surface-descriptor study explicitly finds its descriptor insufficient as a standalone predictor.",
    smallestStep: "Select one openly documented polymorphic family and test whether adding surface descriptors to lattice-energy rankings improves held-out prediction of experimentally observed forms.",
    agentFit: 88,
    scale: "foothold",
    location: { name: "Leipzig, Germany (Ostwald's work on crystallization)", longitude: 12.37, latitude: 51.34 },
    tags: ["polymorphism", "nucleation", "crystal structure", "kinetics"],
    tools: ["ASE", "molecular simulation", "crystal structure databases"],
    sources: [
      { title: "Assessing crystallisation behaviour in molecular crystals through particle rugosities", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC13346652/", kind: "primary", publishedAt: "2026-06-29", passage: "it should not be considered a standalone predictor of crystallisation behaviour" },
      { title: "Polymorph Selection in Charged Colloids in the Second Nucleation Step", url: "https://arxiv.org/abs/2601.03419", kind: "primary", publishedAt: "2026-01-06", sourceType: "preprint" },
    ],
    agentReadiness: "hybrid",
    executionResources: "Use open structures and reported crystallization conditions; some CSD collections require a license. New polymorph validation needs synthesis and diffraction measurements.",
    successCriterion: "Demonstrate improvement over an energy-only ranking on held-out conditions, with unobserved forms treated as untested rather than impossible.",
  }),
  scienceProblem({
    id: "solid-electrolyte-filaments",
    title: "Why does lithium penetrate solid electrolytes?",
    field: "Chemistry",
    subfield: "Battery materials",
    summary: "Even a stiff solid electrolyte can develop metal filaments that short a battery.",
    statement: "Predict the onset and path of lithium penetration through a specified solid electrolyte from measured defects, interfacial contact, electrical conditions, and mechanical properties.",
    whyOpen: "Several routes can produce similar failures, including uneven plating, internal metal deposition, and crack growth. Coupled simulations reproduce selected patterns, but their parameters and mechanisms do not yet transfer reliably between microstructures and operating conditions.",
    smallestStep: "Reproduce a published phase-field calculation, then vary contact defects, electronic leakage, and fracture parameters separately to identify observations that distinguish the proposed failure routes.",
    agentFit: 84,
    scale: "foothold",
    location: { name: "Cambridge, United Kingdom (solid-state battery research)", longitude: 0.12, latitude: 52.21 },
    tags: ["batteries", "solid electrolyte", "filaments", "fracture"],
    tools: ["FEniCS", "phase-field simulation", "sensitivity analysis"],
    sources: [
      { title: "Phase field simulation of dendrite growth in solid-state lithium batteries based on mechanical-thermo-electrochemical coupling", url: "https://arxiv.org/abs/2509.02013", kind: "primary", publishedAt: "2025-09-02", sourceType: "preprint" },
      { title: "Exploring the current engineering challenges of solid-state lithium-sulfur batteries with fundamental materials science: A review", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC13132942/", kind: "survey", publishedAt: "2026-02-12" },
    ],
    agentReadiness: "hybrid",
    executionResources: "A workstation supports small simulations. Parameter calibration and decisive tests require microscopy and controlled electrochemical experiments; simulation stability alone is not material validation.",
    successCriterion: "Recover a published failure regime and produce an uncertainty-aware discrimination plot showing where competing mechanisms predict measurably different onset or propagation.",
  }),
  scienceProblem({
    id: "copper-catalyst-reconstruction",
    title: "Which copper surface makes which carbon product?",
    field: "Chemistry",
    subfield: "Electrocatalysis",
    summary: "Copper changes shape and chemistry while converting carbon dioxide, obscuring its active sites.",
    statement: "Predict how the evolving surface of a copper catalyst controls product selectivity during carbon-dioxide electroreduction under specified potential, electrolyte, and transport conditions.",
    whyOpen: "The starting structure can dissolve, redeposit, or change oxidation state during operation. Several reaction pathways compete, and measurements that average over a changing surface can mistake a correlated structure for the actual active site.",
    smallestStep: "Assemble one condition-matched dataset of operando structural measurements and product distributions, then test whether a time-dependent surface-state model predicts selectivity better than the starting catalyst structure.",
    agentFit: 86,
    scale: "foothold",
    location: { name: "Chiba, Japan (early copper CO2-reduction research)", longitude: 140.12, latitude: 35.61 },
    tags: ["carbon dioxide", "catalysis", "active sites", "surface reconstruction"],
    tools: ["DFT", "microkinetic models", "spectral analysis"],
    sources: [
      { title: "Advancements in Understanding Catalyst Reconstruction During Electrochemical CO2 Reduction", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12380069/", kind: "survey", publishedAt: "2025-04-22", passage: "makes it difficult to understand how actual active sites contribute" },
      { title: "Laser-Synthesized Ligand-Free Cu Nanocatalysts in Electrochemical CO2 Reduction to Methane", url: "https://arxiv.org/abs/2504.13634", kind: "primary", publishedAt: "2025-04-21", sourceType: "preprint" },
    ],
    agentReadiness: "hybrid",
    executionResources: "Published spectra, product tables, and computational models permit hypothesis testing. Sparse synchronized measurements may block identification; new conclusions about active sites need operando experiments.",
    successCriterion: "Beat the static-structure baseline on held-out operating conditions and state which alternative mechanisms remain observationally indistinguishable.",
  }),
  scienceProblem({
    id: "electrode-ion-transferability",
    title: "Can simulations predict ions at a charged surface?",
    field: "Chemistry",
    subfield: "Electrochemical interfaces",
    summary: "Common molecular models can disagree even on whether an ion sticks to an electrode.",
    statement: "Predict ion adsorption free energies at electrified metal-water interfaces across applied potentials and electrolyte compositions, using models that transfer beyond the conditions on which they were fitted.",
    whyOpen: "Standard force-field mixing rules can give qualitatively wrong adsorption. Electronic screening, solvent organization, and applied potential interact, while accurate electronic-structure calculations are too costly to sample every relevant interface configuration.",
    smallestStep: "Reproduce the published Au(111)-water adsorption free-energy comparison, then hold out one ion or potential to test whether fitted electrode-ion parameters genuinely transfer.",
    agentFit: 92,
    scale: "foothold",
    location: { name: "Berkeley, California (electrochemical modeling research)", longitude: -122.27, latitude: 37.87 },
    tags: ["electrochemistry", "solvation", "free energy", "model transfer"],
    tools: ["LAMMPS", "PLUMED", "electronic-structure calculations"],
    sources: [
      { title: "Deriving effective electrode-ion interactions from free-energy profiles at electrochemical interfaces", url: "https://arxiv.org/abs/2507.23031", kind: "primary", publishedAt: "2025-07-30", sourceType: "preprint", passage: "standard mixing rules can lead to qualitatively incorrect descriptions" },
      { title: "Ion and Solvent Modulation of Ferrocene and Decamethylferrocene Oxidation Potentials in Organic Electrolytes as Predicted by Molecular Dynamics Simulations", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11848929/", kind: "primary", publishedAt: "2025-02-11" },
    ],
    agentReadiness: "hybrid",
    executionResources: "Released simulation inputs and a GPU or compute cluster. Electronic-structure agreement is an intermediate benchmark; experimental interface observables are needed for physical validation.",
    successCriterion: "Report converged free energies with sampling errors and a held-out transfer error, distinguishing parameter-fit accuracy from agreement with independent physics.",
  }),
  scienceProblem({
    id: "aerosol-cloud-forcing",
    title: "How much warming do aerosol-cloud changes conceal?",
    field: "Physics",
    subfield: "Climate physics",
    summary: "Airborne particles alter clouds, but the resulting global cooling remains uncertain.",
    statement: "Constrain the radiative forcing caused by human aerosol effects on cloud droplets, water content, and coverage, accounting for cloud regime, time of day, and the representativeness of observed perturbations.",
    whyOpen: "Cloud adjustments can oppose each other and vary over a cloud's lifetime. Recent ship-track and volcanic-eruption studies expose sampling and model errors, but a local perturbation does not automatically establish the global historical forcing.",
    smallestStep: "Reproduce one published ship-track adjustment diagnostic and reweight observations by track age and daylight coverage to quantify the forcing bias introduced by snapshot sampling.",
    agentFit: 93,
    scale: "foothold",
    location: { name: "Holuhraun, Iceland (natural aerosol experiment)", longitude: -16.84, latitude: 64.85 },
    tags: ["climate change", "aerosols", "clouds", "satellite observations"],
    tools: ["xarray", "satellite retrievals", "causal inference"],
    sources: [
      { title: "Substantial Diel Changes of Cloud Adjustments to Aerosols in Ship-tracks", url: "https://arxiv.org/abs/2504.07057", kind: "primary", publishedAt: "2025-04-09", sourceType: "preprint" },
      { title: "Challenges in global climate models to represent cloud response to aerosols: insights from volcanic eruptions", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12816603/", kind: "primary", publishedAt: "2025-12-18" },
    ],
    agentReadiness: "agent-ready",
    executionResources: "Open satellite products and published perturbation datasets. The first result concerns sampling bias in observed cases, not a complete reconstruction of preindustrial aerosols.",
    successCriterion: "Recover the reported local adjustment and quantify the change after sampling correction, with uncertainty from cloud regime and perturbation identification.",
  }),
  scienceProblem({
    id: "amoc-stability-observability",
    title: "How close is Atlantic overturning to a tipping point?",
    field: "Physics",
    subfield: "Ocean circulation",
    summary: "A weakening ocean circulation is not automatically evidence that its collapse threshold is near.",
    statement: "Determine whether observations can distinguish ordinary weakening of the Atlantic overturning circulation from a loss of stability, and constrain any transition threshold without relying on an untested single-variable model.",
    whyOpen: "Ocean-temperature proxies are imperfect measures of overturning, and estimates depend strongly on model structure and data processing. A 2026 robustness study finds that plausible uncertainties greatly broaden inferred tipping times; simulations also differ in abruptness and reversibility.",
    smallestStep: "Reproduce a published early-warning estimator on synthetic circulation series with known stability, then test its false-positive rate under changing noise, proxy bias, and observational coverage.",
    agentFit: 94,
    scale: "frontier",
    introduced: 1961,
    location: { name: "Woods Hole, Massachusetts (Stommel's circulation research)", longitude: -70.67, latitude: 41.52 },
    tags: ["climate change", "AMOC", "tipping points", "identifiability"],
    tools: ["xarray", "stochastic models", "simulation-based calibration"],
    sources: [
      { title: "Extrapolation from historical data cannot reliably predict the time of a potential AMOC collapse", url: "https://arxiv.org/abs/2604.20341", kind: "primary", publishedAt: "2026-04-22", sourceType: "preprint" },
      { title: "Limited impact of Greenland meltwater on abruptness and reversibility of future Atlantic overturning changes", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC13281800/", kind: "primary", publishedAt: "2026-04-15" },
    ],
    agentReadiness: "agent-ready",
    executionResources: "Public climate-model output, proxy records, and synthetic data support estimator testing. A calibrated collapse date may remain unidentifiable from current observations.",
    successCriterion: "Report coverage and false-warning rates against known simulated outcomes, and identify which extra observation would materially distinguish weakening from stability loss.",
  }),
  scienceProblem({
    id: "southern-ocean-carbon-seasonality",
    title: "How much carbon does the Southern Ocean absorb in winter?",
    field: "Physics",
    subfield: "Ocean carbon cycle",
    summary: "Sparse winter measurements leave a major part of the ocean carbon budget uncertain.",
    statement: "Constrain the annual Southern Ocean carbon sink by resolving winter outgassing, sea-ice effects, and measurement biases consistently across ships, floats, and year-round coastal observations.",
    whyOpen: "Ships undersample winter and ice-covered water, while float-derived carbon estimates have sensor and conversion uncertainties. A decade of Rothera observations identifies a sea-ice and stratification mechanism, but one coastal record cannot establish its ocean-wide contribution.",
    smallestStep: "Reproduce the seasonal carbon-flux calculation for the Rothera record, then subsample it to ship-like schedules and quantify the resulting annual-budget bias.",
    agentFit: 95,
    scale: "foothold",
    location: { name: "Rothera Research Station, Antarctica", longitude: -68.13, latitude: -67.57 },
    tags: ["climate change", "ocean carbon", "sea ice", "sampling bias"],
    tools: ["xarray", "PyCO2SYS", "geospatial analysis"],
    sources: [
      { title: "Sea ice controls net ocean uptake of carbon dioxide by regulating wintertime stratification", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12176633/", kind: "primary", publishedAt: "2025-06-18", passage: "spatial and temporal data scarcity" },
    ],
    agentReadiness: "agent-ready",
    executionResources: "Released carbonate-chemistry observations and sea-ice records permit the first test. Ocean-wide attribution requires broader coverage and independently calibrated sensors.",
    successCriterion: "Recover the published seasonal behavior and give a bias interval for annual uptake under realistic missing-winter sampling, including carbonate-system uncertainty.",
  }),
  scienceProblem({
    id: "storm-rainfall-warming-transfer",
    title: "How will individual storms change as climate warms?",
    field: "Physics",
    subfield: "Extreme rainfall",
    summary: "Rainfall-temperature relationships mix physical intensification with changes in which storms occur.",
    statement: "Predict how short-duration rainfall extremes respond to sustained warming across regions, separating changes within storm types from changes in their frequency, organization, and spatial extent.",
    whyOpen: "A 2025 European study explains unusually steep observed scaling largely through a shift between rain types. That does not establish how the mixture changes under future warming elsewhere, and idealized simulations show additional organization-dependent behavior.",
    smallestStep: "Reproduce the rain-type scaling curves from the paper's released source tables and code, then measure their sensitivity to classification uncertainty and temporal aggregation.",
    agentFit: 92,
    scale: "foothold",
    location: { name: "Central Europe (rainfall and lightning observations)", longitude: 10, latitude: 50 },
    tags: ["climate change", "extreme precipitation", "storms", "distribution shift"],
    tools: ["xarray", "radar analysis", "extreme-value statistics"],
    sources: [
      { title: "Super-Clausius-Clapeyron scaling of extreme precipitation explained by shift from stratiform to convective rain type", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12074990/", kind: "primary", publishedAt: "2025-04-28" },
      { title: "Periodic extreme rainfall in a warmer climate due to stronger convectively-coupled waves", url: "https://arxiv.org/abs/2511.19876", kind: "primary", publishedAt: "2025-11-25", sourceType: "preprint" },
    ],
    agentReadiness: "hybrid",
    executionResources: "The paper releases source data and analysis code; DWD weather and RADOLAN radar data are open. Raw BLIDS/EUCLID lightning data require a data-use agreement. Present-day temperature associations do not directly measure future climate response.",
    successCriterion: "Recover the reported within-type and mixed scaling, quantify sensitivity to classification error and aggregation, and specify the additional inputs needed for a held-out regional test.",
  }),
];
